//! Reducer-first ("executable") TLA+ emitter for v2 behaviors.
//!
//! A `behavior X executable { ... }` describes a lifecycle slice that is driven
//! by a pure reducer first and interpreted against a concrete store second. The
//! TLA+ we emit here is the *model* of that reducer: the FSM state plus the
//! projected implementation facts (`memory`), with one action per transition,
//! an explicit `action_taken` trace label, and a `nondet_picks` log so a
//! generated trace can be replayed against the implementation.
//!
//! This is intentionally separate from the legacy verbose emitter in `tla.rs`.

use crate::parser::ast::{
    BehaviorDecl, EffectKind, Expr, FairnessKind, InvariantDecl, StateDecl, TransitionDecl,
    VariableDecl,
};
use crate::transpile::tla::{StateMachineTla, TlcConfig};
use anyhow::Result;

/// Scalar kind of a model variable, used to pick TLA+ type annotations and
/// `TypeOK` domains.
#[derive(Clone, Copy, PartialEq, Eq)]
enum VarTy {
    Int,
    Bool,
    Str,
}

impl VarTy {
    fn from_type_name(name: &str) -> VarTy {
        match name {
            "Bool" | "bool" | "Boolean" => VarTy::Bool,
            "Int" | "Nat" | "Integer" | "i64" | "u64" | "usize" => VarTy::Int,
            _ => VarTy::Str,
        }
    }

    /// Apalache `@type` annotation.
    fn type_anno(self) -> &'static str {
        match self {
            VarTy::Int => "Int",
            VarTy::Bool => "Bool",
            VarTy::Str => "Str",
        }
    }
}

/// A model variable that becomes a TLA+ state variable.
struct ModelVar {
    name: String,
    ty: VarTy,
    init: String,
    /// Whether any transition assigns to it.
    assigned: bool,
    /// For `Str` vars: the ordered, de-duplicated set of literal values it can
    /// take (initial value followed by assigned literals).
    str_domain: Vec<String>,
    /// Const-fold override from an `always(var == literal)` invariant.
    const_value: Option<String>,
}

/// Canonical action label for a transition. The convention is
/// `<from_state>_<event>`, but when an event is already written with its
/// source-state prefix (e.g. `active_revoke` out of `active`) we keep it as-is
/// rather than doubling it (`active_active_revoke`).
fn action_name(from: &str, event: &str) -> String {
    if event == from || event.starts_with(&format!("{}_", from)) {
        event.to_string()
    } else {
        format!("{}_{}", from, event)
    }
}

struct Action {
    name: String,
    from: String,
    to: String,
    guards: Vec<String>,
    /// `(var, rendered_value)` assignments, in declaration order of the sets.
    sets: Vec<(String, String)>,
}

/// Generate the reducer-first TLA+ module for an executable behavior.
pub fn generate_executable_v2(
    behavior: &BehaviorDecl,
    system_name: &str,
    generate_cfg: bool,
) -> Result<StateMachineTla> {
    let module_name = format!("{}_{}", system_name, behavior.name);

    let states = &behavior.states;
    let initial = states
        .iter()
        .find(|s| s.initial)
        .or_else(|| states.first())
        .map(|s| s.name.clone())
        .unwrap_or_else(|| "init".to_string());
    let terminals: Vec<String> = states
        .iter()
        .filter(|s| s.terminal)
        .map(|s| s.name.clone())
        .collect();

    // Does any guard or set use the `now_epoch()` clock primitive? If so we add
    // a `now_epoch` model variable and a synthetic `time_advance` action.
    let uses_now = behavior_uses_now(behavior);

    let mut model_vars = collect_model_vars(behavior, uses_now);
    annotate_assignments(&mut model_vars, &behavior.transitions);
    apply_invariant_constants(&mut model_vars, &behavior.invariants);

    let actions = build_actions(behavior, &model_vars);

    let mut out = String::new();
    let p = &mut out;

    // ---- header ----
    line(p, "\\* AUTO-GENERATED by Intent compiler (executable v2) – do not edit by hand.");
    line(p, &format!("\\* behavior {} executable", behavior.name));
    line(
        p,
        &format!(
            "--------------------------------- MODULE {} ---------------------------------",
            module_name
        ),
    );
    line(p, "EXTENDS Naturals, Sequences, Apalache, Variants");
    line(p, "");

    // ---- state constants ----
    for s in states {
        line(p, &format!("{} == \"{}\"", s.name, s.name));
    }
    line(p, "");

    let state_names: Vec<String> = states.iter().map(|s| s.name.clone()).collect();
    line(p, &format!("States == {{{}}}", state_names.join(", ")));
    line(p, &format!("TerminalStates == {{{}}}", terminals.join(", ")));

    // ---- action labels ----
    let mut labels: Vec<String> = vec!["\"init\"".to_string()];
    for a in &actions {
        labels.push(format!("\"{}\"", a.name));
    }
    if uses_now {
        labels.push("\"time_advance\"".to_string());
    }
    labels.push("\"stutter\"".to_string());
    line(p, &format!("ActionLabels == {{{}}}", labels.join(", ")));
    line(p, "");

    // ---- VARIABLES ----
    line(p, "VARIABLES");
    line(p, "    \\* @type: Str;");
    line(p, "    state,");
    line(p, "    \\* @type: Int;");
    line(p, "    pc,");
    line(p, "    \\* @type: Seq(Str);");
    line(p, "    history,");
    line(p, "    \\* @type: Str;");
    line(p, "    action_taken,");
    line(p, "    \\* @type: Seq(Int);");
    line(p, "    nondet_picks,");
    line(p, "");
    if !behavior.memory.is_empty() {
        line(p, "    \\* projected implementation facts");
    }
    for (i, v) in model_vars.iter().enumerate() {
        let comma = if i + 1 < model_vars.len() { "," } else { "" };
        line(p, &format!("    \\* @type: {};", v.ty.type_anno()));
        line(p, &format!("    {}{}", v.name, comma));
    }
    line(p, "");

    // ---- vars tuple ----
    let model_names: Vec<String> = model_vars.iter().map(|v| v.name.clone()).collect();
    line(p, "vars == <<");
    line(p, "    state, pc, history, action_taken, nondet_picks,");
    line(p, &format!("    {}", model_names.join(", ")));
    line(p, ">>");
    // Action-formula properties are subscripted on the domain state only. The
    // `Stutter` action rewrites `action_taken` and so is not `UNCHANGED vars`,
    // which would make every `[][A]_vars` property fail on a stutter step for
    // reasons that have nothing to do with what it asserts.
    line(p, "");
    line(p, "\\* Domain state, excluding trace bookkeeping.");
    // A two-element tuple of like-typed members is ambiguous to Apalache
    // (tuple or Seq), so the type is always annotated.
    let mut domain_types = vec!["Str".to_string()];
    domain_types.extend(model_vars.iter().map(|v| v.ty.type_anno().to_string()));
    line(
        p,
        &format!("\\* @type: <<{}>>;", domain_types.join(", ")),
    );
    if model_names.is_empty() {
        line(p, "domain_vars == <<state>>");
    } else {
        line(
            p,
            &format!("domain_vars == <<state, {}>>", model_names.join(", ")),
        );
    }
    line(p, "");

    // ---- Init ----
    line(p, "Init ==");
    line(p, &format!("    /\\ state = {}", initial));
    line(p, "    /\\ pc = 0");
    line(p, "    /\\ history = <<>>");
    line(p, "    /\\ action_taken = \"init\"");
    line(p, "    /\\ nondet_picks = <<>>");
    for v in &model_vars {
        line(p, &format!("    /\\ {} = {}", v.name, v.init));
    }
    line(p, "");

    // ---- transition actions ----
    for a in &actions {
        line(p, &format!("{} ==", a.name));
        line(p, &format!("    /\\ state = {}", a.from));
        for g in &a.guards {
            line(p, &format!("    /\\ {}", g));
        }
        line(p, &format!("    /\\ state' = {}", a.to));
        for (var, val) in &a.sets {
            line(p, &format!("    /\\ {}' = {}", var, val));
        }
        let unchanged: Vec<String> = model_vars
            .iter()
            .filter(|v| !a.sets.iter().any(|(n, _)| n == &v.name))
            .map(|v| v.name.clone())
            .collect();
        if !unchanged.is_empty() {
            line(p, &format!("    /\\ UNCHANGED <<{}>>", unchanged.join(", ")));
        }
        line(p, &format!("    /\\ action_taken' = \"{}\"", a.name));
        line(p, "    /\\ nondet_picks' = <<>>");
        line(p, "    /\\ pc' = pc + 1");
        line(p, "    /\\ history' = Append(history, state)");
        line(p, "");
    }

    // ---- synthetic time advance ----
    if uses_now {
        line(p, "time_advance ==");
        line(p, "    /\\ now_epoch' = now_epoch + 1");
        let unchanged: Vec<String> = std::iter::once("state".to_string())
            .chain(["pc".to_string(), "history".to_string()])
            .chain(
                model_vars
                    .iter()
                    .filter(|v| v.name != "now_epoch")
                    .map(|v| v.name.clone()),
            )
            .collect();
        line(p, &format!("    /\\ UNCHANGED <<{}>>", unchanged.join(", ")));
        line(p, "    /\\ action_taken' = \"time_advance\"");
        line(p, "    /\\ nondet_picks' = <<>>");
        line(p, "");
    }

    // ---- Stutter ----
    let stutter_unchanged: Vec<String> = std::iter::once("state".to_string())
        .chain(["pc".to_string(), "history".to_string()])
        .chain(model_names.iter().cloned())
        .collect();
    line(p, "Stutter ==");
    line(
        p,
        &format!("    /\\ UNCHANGED <<{}>>", stutter_unchanged.join(", ")),
    );
    line(p, "    /\\ action_taken' = \"stutter\"");
    line(p, "    /\\ nondet_picks' = <<>>");
    line(p, "");

    // ---- Next ----
    line(p, "Next ==");
    for a in &actions {
        line(p, &format!("    \\/ {}", a.name));
    }
    if uses_now {
        line(p, "    \\/ time_advance");
    }
    line(p, "    \\/ Stutter");
    line(p, "");

    // ---- TypeOK ----
    line(p, "TypeOK ==");
    line(p, "    /\\ state \\in States");
    line(p, "    /\\ pc \\in Nat");
    line(p, "    /\\ action_taken \\in ActionLabels");
    for v in &model_vars {
        line(p, &format!("    /\\ {} {}", v.name, var_domain(v)));
    }
    line(p, "");

    line(p, "HistoryConsistent == Len(history) = pc");
    line(p, "");
    line(p, "NotTerminated == state \\notin TerminalStates");
    line(p, "");

    // ---- temporal properties ----
    let mut prop_names = Vec::new();
    // `memory` flags and model `vars` referenced from properties render as
    // bare TLA variables (not `(state = ...)`), matching how the actions
    // mutate them. See `render_temporal`.
    let bare_names: std::collections::HashSet<String> = behavior
        .memory
        .iter()
        .chain(behavior.variables.iter())
        .map(|v| v.name.clone())
        .collect();
    for prop in &behavior.properties {
        let rendered = render_temporal(&prop.expr, &bare_names);
        line(p, &format!("Prop_{} == {}", prop.name, rendered));
        prop_names.push(format!("Prop_{}", prop.name));
    }

    // ---- user invariants (non-const-folded) ----
    // A bare state name in an invariant body is a predicate, exactly as in a
    // temporal property, so it lowers to `(state = name)`.
    let state_names: std::collections::HashSet<String> =
        behavior.states.iter().map(|s| s.name.clone()).collect();
    let mut inv_names = Vec::new();
    for inv in &behavior.invariants {
        if let Some((var, _lit)) = const_eq_invariant(inv) {
            if model_vars.iter().any(|v| v.name == var) {
                continue; // folded into TypeOK
            }
        }
        let body = render_expr_ctx(
            unwrap_always(&inv.expr),
            ExprCtx {
                states: Some(&state_names),
            },
        );
        let name = pascal_case(&inv.name);
        line(p, &format!("{} == {}", name, body));
        inv_names.push(name);
    }
    if !behavior.properties.is_empty() || !inv_names.is_empty() {
        line(p, "");
    }

    // ---- trace view ----
    let has_view = behavior
        .mbt
        .as_ref()
        .and_then(|m| m.generator.as_ref())
        .map(|g| g.view.is_some())
        .unwrap_or(false);
    if has_view {
        let view_members: Vec<String> = std::iter::once("state".to_string())
            .chain(model_names.iter().cloned())
            .collect();
        // Member TLA+ types: `state` is Str, plus each model var's type.
        let member_types: Vec<&str> = std::iter::once("Str")
            .chain(model_vars.iter().map(|v| v.ty.type_anno()))
            .collect();
        // A homogeneous tuple is ambiguous to Apalache (`<<T,T>>` vs `Seq(T)`),
        // so annotate it. Mixed-type tuples are unambiguous and left bare (this
        // keeps generated output identical to hand-written mixed-type views).
        let homogeneous = member_types.windows(2).all(|w| w[0] == w[1]);
        if homogeneous && member_types.len() > 1 {
            line(p, &format!("\\* @type: <<{}>>;", member_types.join(", ")));
        }
        line(p, &format!("TraceView == <<{}>>", view_members.join(", ")));
        line(p, "");
    }

    // ---- Spec ----
    let fairness_lines = fairness_spec_lines(behavior, &actions);
    if fairness_lines.is_empty() {
        line(p, "Spec ==");
        line(p, "    Init /\\ [][Next]_vars");
    } else {
        line(p, "Spec ==");
        line(p, "    /\\ Init");
        line(p, "    /\\ [][Next]_vars");
        for fl in &fairness_lines {
            line(p, &format!("    /\\ {}", fl));
        }
    }
    line(p, "");
    line(
        p,
        "====================================================================================================",
    );

    // ---- invariants / properties surfaced for verify ----
    let mut invariants = vec!["TypeOK".to_string()];
    if !terminals.is_empty() {
        invariants.push("NotTerminated".to_string());
    }
    invariants.extend(inv_names);

    let tlc_cfg = if generate_cfg {
        Some(build_cfg(&module_name, states, &invariants, &prop_names))
    } else {
        None
    };

    Ok(StateMachineTla {
        content: out,
        module_name,
        invariants,
        properties: prop_names,
        tlc_cfg,
        contract_manifest: None,
        diagnostics: Vec::new(),
        refinement: None,
    })
}

fn line(buf: &mut String, s: &str) {
    buf.push_str(s);
    buf.push('\n');
}

/// Every identifier a transition guard or a temporal property reads.
///
/// Both are assertions over model state, so a `vars` entry either of them
/// mentions has to be declared. Effects are excluded: an assignment target is
/// already handled by `annotate_assignments`.
fn referenced_identifiers(behavior: &BehaviorDecl) -> std::collections::HashSet<String> {
    let mut out = std::collections::HashSet::new();
    for t in &behavior.transitions {
        if let Some(guard) = t.guard.as_ref() {
            collect_expr_idents(guard, &mut out);
        }
    }
    for property in &behavior.properties {
        collect_temporal_idents(&property.expr, &mut out);
    }
    out
}

/// Atoms a temporal property names. A `State` atom is either a lifecycle state
/// or, when it matches a declared field, a reference to that field.
fn collect_temporal_idents(
    e: &crate::parser::ast::TemporalExpr,
    out: &mut std::collections::HashSet<String>,
) {
    use crate::parser::ast::TemporalExpr as T;
    match e {
        T::State(s) => {
            out.insert(s.clone());
        }
        T::Always(i) | T::Eventually(i) | T::Next(i) | T::Not(i) => collect_temporal_idents(i, out),
        T::Until { lhs, rhs }
        | T::Release { lhs, rhs }
        | T::WeakUntil { lhs, rhs }
        | T::StrongRelease { lhs, rhs }
        | T::BinOp { lhs, rhs, .. } => {
            collect_temporal_idents(lhs, out);
            collect_temporal_idents(rhs, out);
        }
        T::AlwaysImplies {
            premise,
            conclusion,
        } => {
            collect_temporal_idents(premise, out);
            collect_temporal_idents(conclusion, out);
        }
        T::Count(_) | T::Int(_) | T::Str(_) | T::Bool(_) => {}
    }
}

fn collect_expr_idents(e: &Expr, out: &mut std::collections::HashSet<String>) {
    match e {
        Expr::Ident(s) => {
            out.insert(s.clone());
        }
        Expr::DottedName(s) => {
            out.insert(s.strip_prefix("memory.").unwrap_or(s).to_string());
        }
        Expr::BinOp { lhs, rhs, .. } | Expr::CompOp { lhs, rhs, .. } | Expr::LogicalOp { lhs, rhs, .. } => {
            collect_expr_idents(lhs, out);
            collect_expr_idents(rhs, out);
        }
        Expr::UnaryOp { expr, .. } => collect_expr_idents(expr, out),
        Expr::Call { args, .. } => args.iter().for_each(|a| collect_expr_idents(a, out)),
        Expr::IfThenElse {
            cond,
            then_expr,
            else_expr,
        } => {
            collect_expr_idents(cond, out);
            collect_expr_idents(then_expr, out);
            collect_expr_idents(else_expr, out);
        }
        _ => {}
    }
}

/// Collect the model variables for the behavior: `memory` block if present,
/// otherwise the numeric/bool `vars` (Uuid/String ids are fixture-only and not
/// part of the model). A `now_epoch` clock var is appended when the spec uses
/// `now_epoch()`.
///
/// When a behavior declares both, `memory` is the state carrier, but any `vars`
/// entry a transition guard or a temporal property actually reads is added too.
/// Without that, the reference lowers to a bare identifier that no `VARIABLES`
/// clause declares, and the spec fails with `Unknown operator` far from the
/// declaration that caused it. Unreferenced `vars` stay out so the model does
/// not grow variables that no action constrains.
fn collect_model_vars(behavior: &BehaviorDecl, uses_now: bool) -> Vec<ModelVar> {
    let mut vars = Vec::new();
    let is_model_ty = |v: &VariableDecl| {
        matches!(
            VarTy::from_type_name(base_type(&v.type_name)),
            VarTy::Int | VarTy::Bool
        )
    };
    let source: Vec<&VariableDecl> = if !behavior.memory.is_empty() {
        let referenced = referenced_identifiers(behavior);
        let memory_names: std::collections::HashSet<&str> =
            behavior.memory.iter().map(|v| v.name.as_str()).collect();
        behavior
            .memory
            .iter()
            .chain(
                behavior
                    .variables
                    .iter()
                    .filter(|v| !memory_names.contains(v.name.as_str()))
                    .filter(|v| referenced.contains(&v.name))
                    .filter(|v| is_model_ty(v)),
            )
            .collect()
    } else {
        behavior
            .variables
            .iter()
            .filter(|v| is_model_ty(v))
            .collect()
    };

    for v in source {
        let ty = VarTy::from_type_name(base_type(&v.type_name));
        let init = match &v.initial_value {
            Some(e) => render_expr(e),
            None => default_for(ty),
        };
        let mut str_domain = Vec::new();
        if ty == VarTy::Str {
            if let Some(Expr::String(s)) = &v.initial_value {
                str_domain.push(s.clone());
            } else if v.initial_value.is_none() {
                str_domain.push(String::new());
            }
        }
        vars.push(ModelVar {
            name: v.name.clone(),
            ty,
            init,
            assigned: false,
            str_domain,
            const_value: None,
        });
    }

    if uses_now && !vars.iter().any(|v| v.name == "now_epoch") {
        vars.push(ModelVar {
            name: "now_epoch".to_string(),
            ty: VarTy::Int,
            init: "0".to_string(),
            assigned: true,
            str_domain: Vec::new(),
            const_value: None,
        });
    }

    vars
}

/// Strip generics/optional markers from a declared type name (`Option<Int>` -> `Int`).
fn base_type(name: &str) -> &str {
    name.trim_end_matches('?')
        .split('<')
        .next()
        .unwrap_or(name)
        .trim()
}

fn default_for(ty: VarTy) -> String {
    match ty {
        VarTy::Int => "0".to_string(),
        VarTy::Bool => "FALSE".to_string(),
        VarTy::Str => "\"\"".to_string(),
    }
}

/// Mark model vars assigned by some transition and accumulate the string-literal
/// values they may take.
fn annotate_assignments(model_vars: &mut [ModelVar], transitions: &[TransitionDecl]) {
    for t in transitions {
        for effect in &t.effects {
            if let EffectKind::Assign { var, value } = &effect.kind {
                if let Some(mv) = model_vars.iter_mut().find(|v| &v.name == var) {
                    mv.assigned = true;
                    if mv.ty == VarTy::Str {
                        if let Expr::String(s) = value {
                            if !mv.str_domain.contains(s) {
                                mv.str_domain.push(s.clone());
                            }
                        }
                    }
                }
            }
        }
    }
}

/// Fold `invariant X { always(var == literal) }` into a const domain for `var`.
fn apply_invariant_constants(model_vars: &mut [ModelVar], invariants: &[InvariantDecl]) {
    for inv in invariants {
        if let Some((var, lit)) = const_eq_invariant(inv) {
            if let Some(mv) = model_vars.iter_mut().find(|v| v.name == var) {
                if !mv.assigned {
                    mv.const_value = Some(lit);
                }
            }
        }
    }
}

/// Recognize `always(var == <int literal>)` (or bare `var == literal`).
fn const_eq_invariant(inv: &InvariantDecl) -> Option<(String, String)> {
    let inner = unwrap_always(&inv.expr);
    if let Expr::CompOp { lhs, op, rhs } = inner {
        if matches!(op, crate::parser::ast::ComparisonOp::Eq) {
            if let (Expr::Ident(name), Expr::Int(n)) = (lhs.as_ref(), rhs.as_ref()) {
                return Some((name.clone(), n.to_string()));
            }
        }
    }
    None
}

fn unwrap_always(expr: &Expr) -> &Expr {
    if let Expr::Call { name, args } = expr {
        if name == "always" && args.len() == 1 {
            return &args[0];
        }
    }
    expr
}

fn var_domain(v: &ModelVar) -> String {
    if let Some(c) = &v.const_value {
        return format!("= {}", c);
    }
    match v.ty {
        VarTy::Bool => "\\in BOOLEAN".to_string(),
        VarTy::Int => "\\in Nat".to_string(),
        VarTy::Str => {
            if v.str_domain.is_empty() {
                "\\in STRING".to_string()
            } else {
                let members: Vec<String> =
                    v.str_domain.iter().map(|s| format!("\"{}\"", s)).collect();
                format!("\\in {{{}}}", members.join(", "))
            }
        }
    }
}

fn build_actions(behavior: &BehaviorDecl, model_vars: &[ModelVar]) -> Vec<Action> {
    let mut actions = Vec::new();
    for t in &behavior.transitions {
        let from = t.from.as_state().unwrap_or("any").to_string();
        let to = match &t.to {
            crate::parser::ast::TransitionTarget::State(s) => s.clone(),
            crate::parser::ast::TransitionTarget::Self_ => from.clone(),
            other => other.to_string_repr(),
        };
        let name = action_name(&from, &t.on_event);

        let guards = t
            .guard
            .as_ref()
            .map(|g| flatten_and(g).iter().map(|c| render_expr(c)).collect())
            .unwrap_or_default();

        let mut sets = Vec::new();
        for effect in &t.effects {
            if let EffectKind::Assign { var, value } = &effect.kind {
                if model_vars.iter().any(|v| &v.name == var) {
                    sets.push((var.clone(), render_expr(value)));
                }
            }
        }

        actions.push(Action {
            name,
            from,
            to,
            guards,
            sets,
        });
    }
    actions
}

/// Map declared fairness specs to per-action `SF_vars`/`WF_vars` lines.
fn fairness_spec_lines(behavior: &BehaviorDecl, actions: &[Action]) -> Vec<String> {
    let mut lines = Vec::new();
    for f in &behavior.fairness {
        // Find the action whose source/target match this fairness pair.
        let action = behavior.transitions.iter().find_map(|t| {
            let from = t.from.as_state()?;
            let to = t.to.as_state()?;
            if from == f.from && (to == f.to || f.alts.iter().any(|a| a == to)) {
                Some(action_name(from, &t.on_event))
            } else {
                None
            }
        });
        let action = match action {
            Some(a) => a,
            None => continue,
        };
        let _ = actions; // action names are derived identically above
        let op = match f.kind {
            FairnessKind::Strong => "SF_vars",
            FairnessKind::Weak => "WF_vars",
        };
        lines.push(format!("{}({})", op, action));
    }
    lines
}

fn behavior_uses_now(behavior: &BehaviorDecl) -> bool {
    behavior.transitions.iter().any(|t| {
        let guard_uses = t.guard.as_ref().map(expr_uses_now).unwrap_or(false);
        let set_uses = t.effects.iter().any(|e| {
            if let EffectKind::Assign { value, .. } = &e.kind {
                expr_uses_now(value)
            } else {
                false
            }
        });
        guard_uses || set_uses
    })
}

fn expr_uses_now(e: &Expr) -> bool {
    match e {
        Expr::Call { name, args } => name == "now_epoch" || args.iter().any(expr_uses_now),
        Expr::BinOp { lhs, rhs, .. }
        | Expr::CompOp { lhs, rhs, .. }
        | Expr::LogicalOp { lhs, rhs, .. } => expr_uses_now(lhs) || expr_uses_now(rhs),
        Expr::UnaryOp { expr, .. } => expr_uses_now(expr),
        _ => false,
    }
}

/// Flatten a top-level `&&` chain into individual conjuncts.
fn flatten_and(e: &Expr) -> Vec<&Expr> {
    match e {
        Expr::LogicalOp {
            lhs,
            op: crate::parser::ast::LogicalOp::And,
            rhs,
        } => {
            let mut v = flatten_and(lhs);
            v.extend(flatten_and(rhs));
            v
        }
        _ => vec![e],
    }
}

/// Rendering context for [`render_expr_ctx`].
///
/// `states` names the behavior's FSM states. In an invariant body a bare state
/// name is a *predicate* ("the machine is in this state"), so it must lower to
/// `(state = name)`; the state constants are `Str`, and emitting the bare name
/// makes Snowcat reject `~pending` with a type error. Contexts that only ever
/// see value expressions (initial values, effect right-hand sides) pass `None`.
#[derive(Clone, Copy, Default)]
struct ExprCtx<'a> {
    states: Option<&'a std::collections::HashSet<String>>,
}

/// Whether a rendered node already carries its own delimiters, so a parent
/// operator does not need to add another pair.
fn renders_self_delimited(e: &Expr) -> bool {
    !matches!(
        e,
        Expr::BinOp { .. } | Expr::CompOp { .. } | Expr::LogicalOp { .. } | Expr::IfThenElse { .. }
    )
}

/// Render an `Expr` to a TLA+ expression string.
fn render_expr(e: &Expr) -> String {
    render_expr_ctx(e, ExprCtx::default())
}

/// Render an `Expr` to TLA+, parenthesising every compound node.
///
/// TLA+ gives `/\` and `\/` the same precedence and rejects them side by side
/// without grouping, and `~` binds tighter than either. Emitting operators
/// unparenthesised therefore produced specs that SANY rejects (`a /\ b \/ c`)
/// or, worse, silently changed meaning: `!(a && b)` lowered to `~a /\ b`.
/// Every compound node now delimits itself, which keeps nesting unambiguous
/// without the double parens that wrapping at both ends would give.
fn render_expr_ctx(e: &Expr, ctx: ExprCtx<'_>) -> String {
    use crate::parser::ast::{ArithOp, ComparisonOp, LogicalOp, UnaryOp};
    match e {
        Expr::Int(n) => n.to_string(),
        Expr::Float(f) => f.to_string(),
        Expr::Duration(d) => d.to_string(),
        Expr::Bool(true) => "TRUE".to_string(),
        Expr::Bool(false) => "FALSE".to_string(),
        Expr::String(s) => format!("\"{}\"", s),
        Expr::Ident(s) => match ctx.states {
            Some(states) if states.contains(s) => format!("(state = {})", s),
            _ => s.clone(),
        },
        Expr::DottedName(s) => s.strip_prefix("memory.").unwrap_or(s).to_string(),
        Expr::Count(s) => format!("count_{}", s),
        Expr::Call { name, args } => {
            if name == "now_epoch" && args.is_empty() {
                "now_epoch".to_string()
            } else {
                let rendered: Vec<String> = args.iter().map(|a| render_expr_ctx(a, ctx)).collect();
                format!("{}({})", name, rendered.join(", "))
            }
        }
        Expr::BinOp { lhs, op, rhs } => {
            let o = match op {
                ArithOp::Add => "+",
                ArithOp::Sub => "-",
                ArithOp::Mul => "*",
                ArithOp::Div => "\\div",
            };
            format!(
                "({} {} {})",
                render_expr_ctx(lhs, ctx),
                o,
                render_expr_ctx(rhs, ctx)
            )
        }
        Expr::CompOp { lhs, op, rhs } => {
            let o = match op {
                ComparisonOp::Lt => "<",
                ComparisonOp::Gt => ">",
                ComparisonOp::Le => "<=",
                ComparisonOp::Ge => ">=",
                ComparisonOp::Eq => "=",
                ComparisonOp::Ne => "#",
            };
            format!(
                "({} {} {})",
                render_expr_ctx(lhs, ctx),
                o,
                render_expr_ctx(rhs, ctx)
            )
        }
        Expr::LogicalOp { lhs, op, rhs } => {
            let o = match op {
                LogicalOp::And => "/\\",
                LogicalOp::Or => "\\/",
            };
            format!(
                "({} {} {})",
                render_expr_ctx(lhs, ctx),
                o,
                render_expr_ctx(rhs, ctx)
            )
        }
        Expr::UnaryOp { op, expr } => {
            let o = match op {
                UnaryOp::Not => "~",
                UnaryOp::Neg => "-",
            };
            // A compound operand already parenthesises itself, so `~` never
            // needs to add a second pair: `!(a && b)` renders `~(a /\ b)`.
            debug_assert!(
                renders_self_delimited(expr) || render_expr_ctx(expr, ctx).starts_with('('),
                "compound operand must delimit itself"
            );
            format!("{}{}", o, render_expr_ctx(expr, ctx))
        }
        Expr::IfThenElse {
            cond,
            then_expr,
            else_expr,
        } => format!(
            "(IF {} THEN {} ELSE {})",
            render_expr_ctx(cond, ctx),
            render_expr_ctx(then_expr, ctx),
            render_expr_ctx(else_expr, ctx)
        ),
        // Emitting `{:?}` here wrote Rust debug text into the spec, which SANY
        // reports as a confusing syntax error far from the real cause. Emit an
        // undefined operator instead: the failure names itself.
        other => {
            format!("UnsupportedIntentExpr \\* {:?}", other)
        }
    }
}

/// Whether a temporal formula asserts anything about the next state.
fn contains_next(e: &crate::parser::ast::TemporalExpr) -> bool {
    use crate::parser::ast::TemporalExpr as T;
    match e {
        T::Next(_) => true,
        T::Always(i) | T::Eventually(i) | T::Not(i) => contains_next(i),
        T::Until { lhs, rhs }
        | T::Release { lhs, rhs }
        | T::WeakUntil { lhs, rhs }
        | T::StrongRelease { lhs, rhs }
        | T::BinOp { lhs, rhs, .. } => contains_next(lhs) || contains_next(rhs),
        T::AlwaysImplies {
            premise,
            conclusion,
        } => contains_next(premise) || contains_next(conclusion),
        T::State(_) | T::Count(_) | T::Int(_) | T::Str(_) | T::Bool(_) => false,
    }
}

/// Render a temporal property to LTL TLA+. State atoms become `(state = name)`;
/// references to driver-local `memory` or model `vars` render as bare TLA
/// variables so properties can assert over them (e.g. containment flags).
fn render_temporal(
    e: &crate::parser::ast::TemporalExpr,
    bare_names: &std::collections::HashSet<String>,
) -> String {
    use crate::parser::ast::{TemporalExpr as T, TemporalOp};
    // Atoms (`State`) already render parenthesized, so only wrap compound
    // operands (binary/implication) to avoid `[]((state = x))` double parens.
    let wrap = |inner: &T| -> String {
        match inner {
            T::BinOp { .. } | T::AlwaysImplies { .. } => {
                format!("({})", render_temporal(inner, bare_names))
            }
            _ => render_temporal(inner, bare_names),
        }
    };
    match e {
        // TLA+ has no LTL `X`; a next-state assertion is a primed expression,
        // and a temporal formula containing one has to be an action formula.
        // `always(P => !next(P))` is therefore `[][P => ~(P')]_vars`, not
        // `[](P => ~X(P))`, which SANY rejects as an unknown operator.
        T::Always(inner) if contains_next(inner) => {
            format!("[][{}]_domain_vars", render_temporal(inner, bare_names))
        }
        T::Always(inner) => format!("[]{}", wrap(inner)),
        T::Eventually(inner) => format!("<>{}", wrap(inner)),
        T::Next(inner) => format!("({})'", render_temporal(inner, bare_names)),
        T::Not(inner) => format!("~({})", render_temporal(inner, bare_names)),
        T::State(s) => {
            // A `memory` flag or model `vars` reference renders as the bare
            // TLA variable; only lifecycle states become `(state = name)`.
            if bare_names.contains(s) {
                s.clone()
            } else {
                format!("(state = {})", s)
            }
        }
        T::Count(s) => format!("count_{}", s),
        T::Int(n) => n.to_string(),
        T::Str(s) => format!("\"{}\"", s),
        T::Bool(b) => if *b { "TRUE".to_string() } else { "FALSE".to_string() },
        T::Until { lhs, rhs } => format!(
            "({}) ~> ({})",
            render_temporal(lhs, bare_names),
            render_temporal(rhs, bare_names)
        ),
        T::Release { lhs, rhs } | T::WeakUntil { lhs, rhs } | T::StrongRelease { lhs, rhs } => {
            format!(
                "({}) ~> ({})",
                render_temporal(lhs, bare_names),
                render_temporal(rhs, bare_names)
            )
        }
        T::AlwaysImplies { premise, conclusion } => format!(
            "[]({} => <>({}))",
            render_temporal(premise, bare_names),
            render_temporal(conclusion, bare_names)
        ),
        T::BinOp { lhs, op, rhs } => {
            let o = match op {
                TemporalOp::And => "/\\",
                TemporalOp::Or => "\\/",
                TemporalOp::Implies => "=>",
                TemporalOp::Iff => "<=>",
                TemporalOp::Lt => "<",
                TemporalOp::Le => "<=",
                TemporalOp::Gt => ">",
                TemporalOp::Ge => ">=",
                TemporalOp::Eq => "=",
                TemporalOp::Ne => "#",
            };
            format!(
                "{} {} {}",
                render_temporal(lhs, bare_names),
                o,
                render_temporal(rhs, bare_names)
            )
        }
    }
}

fn pascal_case(name: &str) -> String {
    name.split('_')
        .filter(|p| !p.is_empty())
        .map(|p| {
            let mut c = p.chars();
            match c.next() {
                Some(first) => first.to_uppercase().collect::<String>() + c.as_str(),
                None => String::new(),
            }
        })
        .collect()
}

fn build_cfg(
    module_name: &str,
    states: &[StateDecl],
    invariants: &[String],
    properties: &[String],
) -> TlcConfig {
    let mut cfg = String::new();
    cfg.push_str("\\* TLC/Apalache configuration (executable v2)\n");
    cfg.push_str(&format!("\\* Module: {}\n\n", module_name));
    cfg.push_str("SPECIFICATION Spec\n\n");
    cfg.push_str("CONSTANTS\n");
    for s in states {
        cfg.push_str(&format!("    {} = \"{}\"\n", s.name, s.name));
    }
    cfg.push('\n');
    if !invariants.is_empty() {
        cfg.push_str("INVARIANTS\n");
        for inv in invariants {
            cfg.push_str(&format!("    {}\n", inv));
        }
        cfg.push('\n');
    }
    if !properties.is_empty() {
        cfg.push_str("PROPERTIES\n");
        for prop in properties {
            cfg.push_str(&format!("    {}\n", prop));
        }
        cfg.push('\n');
    }
    cfg.push_str("CHECK_DEADLOCK FALSE\n");
    TlcConfig {
        content: cfg,
        filename: format!("{}.cfg", module_name),
    }
}
