\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE MentalModelDemo_OrderDoesntMatter  -----------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { s1, s2, s3 }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
s1 == "s1"
s2 == "s2"
s3 == "s3"

States == {
    s1, s2, s3
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Str });
    Channel_queue     \* Message queue for Channel

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Str })>>;
vars == <<state, pc, history, event_queue, Channel_queue>>

Init ==
    /\ state = s1
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ Channel_queue = <<>>

\* Transition actions
s1_version_a ==
    /\ state = s1
    /\ state' = s2
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ Channel_queue' = Channel_queue \o <<[type |-> "Log", arg0 |-> "first"], [type |-> "Log", arg0 |-> "second"], [type |-> "Log", arg0 |-> "third"]>>

s2_version_b ==
    /\ state = s2
    /\ state' = s3
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ Channel_queue' = Channel_queue \o <<[type |-> "Log", arg0 |-> "third"], [type |-> "Log", arg0 |-> "first"], [type |-> "Log", arg0 |-> "second"]>>

Next ==
    \/ s1_version_a
    \/ s2_version_b
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_s1 == <>(state = s1)
CanReach_s2 == <>(state = s2)
CanReach_s3 == <>(state = s3)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     s1 = "s1"
\*     s2 = "s2"
\*     s3 = "s3"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=====================================================
