\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------------  MODULE OrderPayment_OrderProcessing  ------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { pending, payment_requested, completed, failed }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
pending == "pending"
payment_requested == "payment_requested"
completed == "completed"
failed == "failed"

States == {
    pending, payment_requested, completed, failed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Int, arg1: Int });
    PaymentService_queue,    \* Message queue for PaymentService
    \* @type: Int;
    orderID     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Int, arg1: Int }), Int>>;
vars == <<state, pc, history, event_queue, PaymentService_queue, orderID>>

Init ==
    /\ state = pending
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ PaymentService_queue = <<>>
    /\ orderID = 0

\* Transition actions
pending_create_order ==
    /\ state = pending
    /\ state' = payment_requested
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = PaymentService_queue \o <<[type |-> "PaymentRequest", arg0 |-> 123, arg1 |-> 100]>>
    /\ orderID' = 123

payment_requested_payment_success ==
    /\ state = payment_requested
    /\ state' = completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = Tail(PaymentService_queue)
    /\ UNCHANGED <<orderID>>

payment_requested_payment_failure ==
    /\ state = payment_requested
    /\ state' = failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = Tail(PaymentService_queue)
    /\ UNCHANGED <<orderID>>

Next ==
    \/ pending_create_order
    \/ payment_requested_payment_success
    \/ payment_requested_payment_failure
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_pending == <>(state = pending)
CanReach_payment_requested == <>(state = payment_requested)
CanReach_completed == <>(state = completed)
CanReach_failed == <>(state = failed)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     pending = "pending"
\*     payment_requested = "payment_requested"
\*     completed = "completed"
\*     failed = "failed"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

================================================
