\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------  MODULE OrderPayment_PaymentProcessing  --------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, processing, confirmed }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
processing == "processing"
confirmed == "confirmed"

States == {
    idle, processing, confirmed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Int, arg1: Bool });
    PaymentService_queue,    \* Message queue for PaymentService
    \* @type: Int;
    processingOrderId     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Int, arg1: Bool }), Int>>;
vars == <<state, pc, history, event_queue, PaymentService_queue, processingOrderId>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ PaymentService_queue = <<>>
    /\ processingOrderId = 0

\* Transition actions
idle_receive_payment ==
    /\ state = idle
    /\ state' = processing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = Tail(PaymentService_queue)
    /\ UNCHANGED <<processingOrderId>>

processing_confirm ==
    /\ state = processing
    /\ state' = confirmed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = PaymentService_queue \o <<[type |-> "PaymentConfirmed", arg0 |-> 123, arg1 |-> TRUE]>>
    /\ UNCHANGED <<processingOrderId>>

Next ==
    \/ idle_receive_payment
    \/ processing_confirm
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_processing == <>(state = processing)
CanReach_confirmed == <>(state = confirmed)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     processing = "processing"
\*     confirmed = "confirmed"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==================================================
