\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------  MODULE OrderIndependence_VersionC  ----------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { start, done }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
start == "start"
done == "done"

States == {
    start, done
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Int });
    Channel_queue,    \* Message queue for Channel
    \* @type: Int;
    counter,    \* Data variable (extracted)
    \* @type: Int;
    other     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Int }), Int, Int>>;
vars == <<state, pc, history, event_queue, Channel_queue, counter, other>>

Init ==
    /\ state = start
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ Channel_queue = <<>>
    /\ counter = 0
    /\ other = 0

\* Transition actions
start_go ==
    /\ state = start
    /\ state' = done
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ Channel_queue' = Channel_queue \o <<[type |-> "Value", arg0 |-> counter]>>
    /\ counter' = (counter + 1)
    /\ other' = 42

Next ==
    \/ start_go
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_start == <>(state = start)
CanReach_done == <>(state = done)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     start = "start"
\*     done = "done"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==============================================
