\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------  MODULE ProducerConsumer_Consumer  ---------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { waiting, received }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
waiting == "waiting"
received == "received"

States == {
    waiting, received
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str });
    Channel_queue     \* Message queue for Channel

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue, Channel_queue>>

Init ==
    /\ state = waiting
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ Channel_queue = <<>>

\* Transition actions
waiting_consume ==
    /\ state = waiting
    /\ state' = received
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ Channel_queue' = Tail(Channel_queue)

Next ==
    \/ waiting_consume
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_waiting == <>(state = waiting)
CanReach_received == <>(state = received)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     waiting = "waiting"
\*     received = "received"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=============================================
