\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------  MODULE ProducerConsumer_Producer  ---------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, sent }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
sent == "sent"

States == {
    idle, sent
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Int });
    Channel_queue     \* Message queue for Channel

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Int })>>;
vars == <<state, pc, history, event_queue, Channel_queue>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ Channel_queue = <<>>

\* Transition actions
idle_produce ==
    /\ state = idle
    /\ state' = sent
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ Channel_queue' = Channel_queue \o <<[type |-> "Data", arg0 |-> 42]>>

Next ==
    \/ idle_produce
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_sent == <>(state = sent)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     sent = "sent"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=============================================
