\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------  MODULE RequestResponse_Server  ------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { listening, processing, responded }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
listening == "listening"
processing == "processing"
responded == "responded"

States == {
    listening, processing, responded
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str });
    RequestChannel_queue,    \* Message queue for RequestChannel
    \* @type: Seq({ type: Str, arg0: Int, arg1: Int });
    ResponseChannel_queue,    \* Message queue for ResponseChannel
    \* @type: Int;
    queryId     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str }), Seq({ type: Str, arg0: Int, arg1: Int }), Int>>;
vars == <<state, pc, history, event_queue, RequestChannel_queue, ResponseChannel_queue, queryId>>

Init ==
    /\ state = listening
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ RequestChannel_queue = <<>>
    /\ ResponseChannel_queue = <<>>
    /\ queryId = 0

\* Transition actions
listening_receive_query ==
    /\ state = listening
    /\ state' = processing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ RequestChannel_queue' = Tail(RequestChannel_queue)
    /\ UNCHANGED <<ResponseChannel_queue, queryId>>

processing_send_result ==
    /\ state = processing
    /\ state' = responded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ ResponseChannel_queue' = ResponseChannel_queue \o <<[type |-> "Result", arg0 |-> 1, arg1 |-> 42]>>
    /\ UNCHANGED <<RequestChannel_queue, queryId>>

Next ==
    \/ listening_receive_query
    \/ processing_send_result
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_listening == <>(state = listening)
CanReach_processing == <>(state = processing)
CanReach_responded == <>(state = responded)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     listening = "listening"
\*     processing = "processing"
\*     responded = "responded"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==========================================
