\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------  MODULE RequestResponse_Client  ------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, waiting, done }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
waiting == "waiting"
done == "done"

States == {
    idle, waiting, done
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Int });
    RequestChannel_queue,    \* Message queue for RequestChannel
    \* @type: Seq({ type: Str });
    ResponseChannel_queue,    \* Message queue for ResponseChannel
    \* @type: Int;
    requestId     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Int }), Seq({ type: Str }), Int>>;
vars == <<state, pc, history, event_queue, RequestChannel_queue, ResponseChannel_queue, requestId>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ RequestChannel_queue = <<>>
    /\ ResponseChannel_queue = <<>>
    /\ requestId = 0

\* Transition actions
idle_send_request ==
    /\ state = idle
    /\ state' = waiting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ RequestChannel_queue' = RequestChannel_queue \o <<[type |-> "Query", arg0 |-> 1]>>
    /\ requestId' = 1
    /\ UNCHANGED <<ResponseChannel_queue>>

waiting_receive_response ==
    /\ state = waiting
    /\ state' = done
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ ResponseChannel_queue' = Tail(ResponseChannel_queue)
    /\ UNCHANGED <<RequestChannel_queue, requestId>>

Next ==
    \/ idle_send_request
    \/ waiting_receive_response
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_waiting == <>(state = waiting)
CanReach_done == <>(state = done)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     waiting = "waiting"
\*     done = "done"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==========================================
