\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------  MODULE PaymentPlatform_SettlementSaga  --------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { initiated, reserving, reserved, committing, committed, compensating, compensated, saga_pending, saga_completed, saga_failed }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
initiated == "initiated"
reserving == "reserving"
reserved == "reserved"
committing == "committing"
committed == "committed"
compensating == "compensating"
compensated == "compensated"
saga_pending == "saga_pending"
saga_completed == "saga_completed"
saga_failed == "saga_failed"

States == {
    initiated, reserving, reserved, committing, committed, compensating, compensated, saga_pending, saga_completed, saga_failed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {initiated, saga_pending}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
initiated_begin ==
    /\ state = initiated
    /\ state' = reserving
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

reserving_reserve_success ==
    /\ state = reserving
    /\ state' = reserved
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

reserving_reserve_failed ==
    /\ state = reserving
    /\ state' = compensating
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

reserved_commit_cmd ==
    /\ state = reserved
    /\ state' = committing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

committing_commit_success ==
    /\ state = committing
    /\ state' = committed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

committing_commit_failed ==
    /\ state = committing
    /\ state' = compensating
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensating_undo_complete ==
    /\ state = compensating
    /\ state' = compensated
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

saga_pending_success ==
    /\ state = saga_pending
    /\ state' = saga_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

saga_pending_failure ==
    /\ state = saga_pending
    /\ state' = saga_failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ initiated_begin
    \/ reserving_reserve_success
    \/ reserving_reserve_failed
    \/ reserved_commit_cmd
    \/ committing_commit_success
    \/ committing_commit_failed
    \/ compensating_undo_complete
    \/ saga_pending_success
    \/ saga_pending_failure
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_reserving_to_reserved_or_compensating == SF_vars(reserving_reserve_success) \/ SF_vars(reserving_reserve_failed)
Fairness_committing_to_committed_or_compensating == SF_vars(committing_commit_success) \/ SF_vars(committing_commit_failed)
Fairness_compensating_to_compensated == SF_vars(compensating_undo_complete)
Fairness_saga_pending_to_saga_completed_or_saga_failed == SF_vars(saga_pending_success) \/ SF_vars(saga_pending_failure)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {committed, compensated, saga_completed, saga_failed}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_completion == []((state = initiated) => (<>((state = committed) \/ (state = compensated))))
Prop_Saga_eventual_completion == []((state = saga_pending) => (<>((state = saga_completed) \/ (state = saga_failed))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {committed, compensated, saga_completed, saga_failed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_initiated == <>(state = initiated)
CanReach_reserving == <>(state = reserving)
CanReach_reserved == <>(state = reserved)
CanReach_committing == <>(state = committing)
CanReach_committed == <>(state = committed)
CanReach_compensating == <>(state = compensating)
CanReach_compensated == <>(state = compensated)
CanReach_saga_pending == <>(state = saga_pending)
CanReach_saga_completed == <>(state = saga_completed)
CanReach_saga_failed == <>(state = saga_failed)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     initiated = "initiated"
\*     reserving = "reserving"
\*     reserved = "reserved"
\*     committing = "committing"
\*     committed = "committed"
\*     compensating = "compensating"
\*     compensated = "compensated"
\*     saga_pending = "saga_pending"
\*     saga_completed = "saga_completed"
\*     saga_failed = "saga_failed"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==================================================
