\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE PaymentPlatform_TransactionLifecycle  --------------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { pending, validating, authorizing, captured, settled, failed, refunded, retry_pending, retry_succeeded, retry_exhausted, circuitbreaker_closed, circuitbreaker_open, circuitbreaker_half_open, timeout_pending, timeout_completed, timeout_timed_out }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
pending == "pending"
validating == "validating"
authorizing == "authorizing"
captured == "captured"
settled == "settled"
failed == "failed"
refunded == "refunded"
retry_pending == "retry_pending"
retry_succeeded == "retry_succeeded"
retry_exhausted == "retry_exhausted"
circuitbreaker_closed == "circuitbreaker_closed"
circuitbreaker_open == "circuitbreaker_open"
circuitbreaker_half_open == "circuitbreaker_half_open"
timeout_pending == "timeout_pending"
timeout_completed == "timeout_completed"
timeout_timed_out == "timeout_timed_out"

States == {
    pending, validating, authorizing, captured, settled, failed, refunded, retry_pending, retry_succeeded, retry_exhausted, circuitbreaker_closed, circuitbreaker_open, circuitbreaker_half_open, timeout_pending, timeout_completed, timeout_timed_out
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Int;
    amount     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Int>>;
vars == <<state, pc, history, event_queue, amount>>

Init ==
    /\ state \in {pending, retry_pending, circuitbreaker_closed, timeout_pending}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ amount = 0

\* Transition actions
pending_received ==
    /\ state = pending
    /\ state' = validating
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

validating_valid ==
    /\ state = validating
    /\ (amount > 0)
    /\ state' = authorizing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

validating_invalid ==
    /\ state = validating
    /\ state' = failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

authorizing_authorized ==
    /\ state = authorizing
    /\ state' = captured
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

authorizing_declined ==
    /\ state = authorizing
    /\ state' = failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

captured_batch_close ==
    /\ state = captured
    /\ state' = settled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

captured_refund_request ==
    /\ state = captured
    /\ state' = refunded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

retry_pending_success ==
    /\ state = retry_pending
    /\ state' = retry_succeeded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

retry_pending_failure ==
    /\ state = retry_pending
    /\ state' = retry_exhausted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

circuitbreaker_closed_failures_exceeded ==
    /\ state = circuitbreaker_closed
    /\ state' = circuitbreaker_open
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

circuitbreaker_open_recovery_elapsed ==
    /\ state = circuitbreaker_open
    /\ state' = circuitbreaker_half_open
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

circuitbreaker_half_open_success ==
    /\ state = circuitbreaker_half_open
    /\ state' = circuitbreaker_closed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

circuitbreaker_half_open_failure ==
    /\ state = circuitbreaker_half_open
    /\ state' = circuitbreaker_open
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

timeout_pending_success ==
    /\ state = timeout_pending
    /\ state' = timeout_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

timeout_pending_timeout ==
    /\ state = timeout_pending
    /\ state' = timeout_timed_out
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<amount>>

Next ==
    \/ pending_received
    \/ validating_valid
    \/ validating_invalid
    \/ authorizing_authorized
    \/ authorizing_declined
    \/ captured_batch_close
    \/ captured_refund_request
    \/ retry_pending_success
    \/ retry_pending_failure
    \/ circuitbreaker_closed_failures_exceeded
    \/ circuitbreaker_open_recovery_elapsed
    \/ circuitbreaker_half_open_success
    \/ circuitbreaker_half_open_failure
    \/ timeout_pending_success
    \/ timeout_pending_timeout
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_pending_to_validating_or_failed == SF_vars(pending_received)
Fairness_authorizing_to_captured_or_failed == SF_vars(authorizing_authorized) \/ SF_vars(authorizing_declined)
Fairness_retry_pending_to_retry_succeeded_or_retry_exhausted == SF_vars(retry_pending_success) \/ SF_vars(retry_pending_failure)
Fairness_circuitbreaker_half_open_to_circuitbreaker_closed_or_circuitbreaker_open == SF_vars(circuitbreaker_half_open_success) \/ SF_vars(circuitbreaker_half_open_failure)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {settled, failed, refunded, retry_succeeded, retry_exhausted, timeout_completed, timeout_timed_out}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_completion == []((state = pending) => (<>(((state = settled) \/ (state = failed)) \/ (state = refunded))))
Prop_no_partial_settlement == []((state = captured) => (<>((state = settled) \/ (state = refunded))))
Prop_CircuitBreaker_eventual_recovery == []((state = circuitbreaker_open) => (<>(state = circuitbreaker_half_open)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {settled, failed, refunded, retry_succeeded, retry_exhausted, timeout_completed, timeout_timed_out})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_pending == <>(state = pending)
CanReach_validating == <>(state = validating)
CanReach_authorizing == <>(state = authorizing)
CanReach_captured == <>(state = captured)
CanReach_settled == <>(state = settled)
CanReach_failed == <>(state = failed)
CanReach_refunded == <>(state = refunded)
CanReach_retry_pending == <>(state = retry_pending)
CanReach_retry_succeeded == <>(state = retry_succeeded)
CanReach_retry_exhausted == <>(state = retry_exhausted)
CanReach_circuitbreaker_closed == <>(state = circuitbreaker_closed)
CanReach_circuitbreaker_open == <>(state = circuitbreaker_open)
CanReach_circuitbreaker_half_open == <>(state = circuitbreaker_half_open)
CanReach_timeout_pending == <>(state = timeout_pending)
CanReach_timeout_completed == <>(state = timeout_completed)
CanReach_timeout_timed_out == <>(state = timeout_timed_out)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     pending = "pending"
\*     validating = "validating"
\*     authorizing = "authorizing"
\*     captured = "captured"
\*     settled = "settled"
\*     failed = "failed"
\*     refunded = "refunded"
\*     retry_pending = "retry_pending"
\*     retry_succeeded = "retry_succeeded"
\*     retry_exhausted = "retry_exhausted"
\*     circuitbreaker_closed = "circuitbreaker_closed"
\*     circuitbreaker_open = "circuitbreaker_open"
\*     circuitbreaker_half_open = "circuitbreaker_half_open"
\*     timeout_pending = "timeout_pending"
\*     timeout_completed = "timeout_completed"
\*     timeout_timed_out = "timeout_timed_out"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

========================================================
