\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------  MODULE DistributedCache_NodeLifecycle  --------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants, FiniteSets

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { joining, follower, candidate, leader, leaving, leaderelection_follower, leaderelection_candidate, leaderelection_leader }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* Constants
CONSTANTS
    \* @type: Set(Str);
    replicas

\* State values (defined as strings for Apalache)
joining == "joining"
follower == "follower"
candidate == "candidate"
leader == "leader"
leaving == "leaving"
leaderelection_follower == "leaderelection_follower"
leaderelection_candidate == "leaderelection_candidate"
leaderelection_leader == "leaderelection_leader"

States == {
    joining, follower, candidate, leader, leaving, leaderelection_follower, leaderelection_candidate, leaderelection_leader
}

VARIABLES
    \* @type: Str -> Str;
    state,      \* Per-node state (function from nodes to States)
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str -> Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

\* CInit: constant initializer for Apalache (--cinit=CInit)
\* Provides a small default value for bounded model checking.
CInit ==
    replicas = {"n1", "n2", "n3"}

Init ==
    /\ state \in [replicas -> {joining, leaderelection_follower}]
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
joining_cluster_joined(n) ==
    /\ n \in replicas
    /\ state[n] = joining
    /\ state' = [state EXCEPT ![n] = follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

follower_election_timeout(n) ==
    /\ n \in replicas
    /\ state[n] = follower
    /\ state' = [state EXCEPT ![n] = candidate]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

follower_shutdown(n) ==
    /\ n \in replicas
    /\ state[n] = follower
    /\ state' = [state EXCEPT ![n] = leaving]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

candidate_majority_vote(n) ==
    /\ n \in replicas
    /\ state[n] = candidate
    /\ state' = [state EXCEPT ![n] = leader]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

candidate_higher_term_seen(n) ==
    /\ n \in replicas
    /\ state[n] = candidate
    /\ state' = [state EXCEPT ![n] = follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

candidate_election_lost(n) ==
    /\ n \in replicas
    /\ state[n] = candidate
    /\ state' = [state EXCEPT ![n] = follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leader_higher_term_detected(n) ==
    /\ n \in replicas
    /\ state[n] = leader
    /\ state' = [state EXCEPT ![n] = follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leader_shutdown(n) ==
    /\ n \in replicas
    /\ state[n] = leader
    /\ state' = [state EXCEPT ![n] = leaving]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leaderelection_follower_election_timeout(n) ==
    /\ n \in replicas
    /\ state[n] = leaderelection_follower
    /\ state' = [state EXCEPT ![n] = leaderelection_candidate]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leaderelection_candidate_majority_vote(n) ==
    /\ n \in replicas
    /\ state[n] = leaderelection_candidate
    /\ state' = [state EXCEPT ![n] = leaderelection_leader]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leaderelection_candidate_higher_term_seen(n) ==
    /\ n \in replicas
    /\ state[n] = leaderelection_candidate
    /\ state' = [state EXCEPT ![n] = leaderelection_follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

leaderelection_leader_higher_term_detected(n) ==
    /\ n \in replicas
    /\ state[n] = leaderelection_leader
    /\ state' = [state EXCEPT ![n] = leaderelection_follower]
    /\ pc' = pc + 1
    /\ history' = Append(history, state[n])
    /\ event_queue' = event_queue

Next ==
    \/ \E n \in replicas : joining_cluster_joined(n)
    \/ \E n \in replicas : follower_election_timeout(n)
    \/ \E n \in replicas : follower_shutdown(n)
    \/ \E n \in replicas : candidate_majority_vote(n)
    \/ \E n \in replicas : candidate_higher_term_seen(n)
    \/ \E n \in replicas : candidate_election_lost(n)
    \/ \E n \in replicas : leader_higher_term_detected(n)
    \/ \E n \in replicas : leader_shutdown(n)
    \/ \E n \in replicas : leaderelection_follower_election_timeout(n)
    \/ \E n \in replicas : leaderelection_candidate_majority_vote(n)
    \/ \E n \in replicas : leaderelection_candidate_higher_term_seen(n)
    \/ \E n \in replicas : leaderelection_leader_higher_term_detected(n)
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_joining_to_follower == \A n \in replicas : SF_vars(joining_cluster_joined(n))
Fairness_candidate_to_leader_or_follower == \A n \in replicas : (SF_vars(candidate_majority_vote(n)) \/ SF_vars(candidate_higher_term_seen(n)) \/ SF_vars(candidate_election_lost(n)))
Fairness_leaderelection_candidate_to_leaderelection_leader_or_leaderelection_follower == \A n \in replicas : (SF_vars(leaderelection_candidate_majority_vote(n)) \/ SF_vars(leaderelection_candidate_higher_term_seen(n)))
Fairness_leaderelection_leader_to_leaderelection_follower == \A n \in replicas : WF_vars(leaderelection_leader_higher_term_detected(n))

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in [replicas -> States]
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {leaving}

\* Once in terminal state, cannot leave
TerminalStable ==
    \A n \in replicas : (state[n] \in TerminalStates) => (state'[n] \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_single_leader == []((Cardinality({n \in replicas : state[n] = leader})) <= (1))
Prop_no_leaderless_periods == [](<>((Cardinality({n \in replicas : state[n] = leader})) >= (1)))
Prop_LeaderElection_single_leader == []((Cardinality({n \in replicas : state[n] = leaderelection_leader})) <= (1))
Prop_LeaderElection_eventual_leader == [](((\E n \in replicas : state[n] = leaderelection_follower) \/ (\E n \in replicas : state[n] = leaderelection_candidate)) => (<>((\E n \in replicas : state[n] = leaderelection_leader) \/ (\E n \in replicas : state[n] = leaderelection_follower))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(\A n \in replicas : state[n] \in {leaving})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_joining == <>(\E n \in replicas : state[n] = joining)
CanReach_follower == <>(\E n \in replicas : state[n] = follower)
CanReach_candidate == <>(\E n \in replicas : state[n] = candidate)
CanReach_leader == <>(\E n \in replicas : state[n] = leader)
CanReach_leaving == <>(\E n \in replicas : state[n] = leaving)
CanReach_leaderelection_follower == <>(\E n \in replicas : state[n] = leaderelection_follower)
CanReach_leaderelection_candidate == <>(\E n \in replicas : state[n] = leaderelection_candidate)
CanReach_leaderelection_leader == <>(\E n \in replicas : state[n] = leaderelection_leader)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     joining = "joining"
\*     follower = "follower"
\*     candidate = "candidate"
\*     leader = "leader"
\*     leaving = "leaving"
\*     leaderelection_follower = "leaderelection_follower"
\*     leaderelection_candidate = "leaderelection_candidate"
\*     leaderelection_leader = "leaderelection_leader"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==================================================
