\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------  MODULE DistributedCache_Failover  ---------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { stable, degraded, recovering, recovered, unrecoverable }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
stable == "stable"
degraded == "degraded"
recovering == "recovering"
recovered == "recovered"
unrecoverable == "unrecoverable"

States == {
    stable, degraded, recovering, recovered, unrecoverable
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = stable
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
stable_node_failure ==
    /\ state = stable
    /\ state' = degraded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

degraded_failover_initiated ==
    /\ state = degraded
    /\ state' = recovering
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

degraded_quorum_lost ==
    /\ state = degraded
    /\ state' = unrecoverable
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

recovering_recovery_complete ==
    /\ state = recovering
    /\ state' = recovered
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

recovering_recovery_failed ==
    /\ state = recovering
    /\ state' = degraded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ stable_node_failure
    \/ degraded_failover_initiated
    \/ degraded_quorum_lost
    \/ recovering_recovery_complete
    \/ recovering_recovery_failed
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_degraded_to_recovering_or_unrecoverable == SF_vars(degraded_failover_initiated) \/ SF_vars(degraded_quorum_lost)
Fairness_recovering_to_recovered_or_degraded == SF_vars(recovering_recovery_complete) \/ SF_vars(recovering_recovery_failed)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {recovered, unrecoverable}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_automatic_failover == []((state = degraded) => (<>((state = recovering) \/ (state = unrecoverable))))
Prop_bounded_downtime == []((state = degraded) => (<>(((state = stable) \/ (state = recovered)) \/ (state = unrecoverable))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {recovered, unrecoverable})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_stable == <>(state = stable)
CanReach_degraded == <>(state = degraded)
CanReach_recovering == <>(state = recovering)
CanReach_recovered == <>(state = recovered)
CanReach_unrecoverable == <>(state = unrecoverable)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     stable = "stable"
\*     degraded = "degraded"
\*     recovering = "recovering"
\*     recovered = "recovered"
\*     unrecoverable = "unrecoverable"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=============================================
