\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE DistributedCache_WriteReplication  -----------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { local_written, replicating, quorum_reached, quorum_failed, quorum_pending, quorum_quorum_reached, quorum_quorum_lost, lease_available, lease_held, lease_expired }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
local_written == "local_written"
replicating == "replicating"
quorum_reached == "quorum_reached"
quorum_failed == "quorum_failed"
quorum_pending == "quorum_pending"
quorum_quorum_reached == "quorum_quorum_reached"
quorum_quorum_lost == "quorum_quorum_lost"
lease_available == "lease_available"
lease_held == "lease_held"
lease_expired == "lease_expired"

States == {
    local_written, replicating, quorum_reached, quorum_failed, quorum_pending, quorum_quorum_reached, quorum_quorum_lost, lease_available, lease_held, lease_expired
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {local_written, quorum_pending, lease_available}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
local_written_forward_to_replicas ==
    /\ state = local_written
    /\ state' = replicating
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

replicating_majority_acked ==
    /\ state = replicating
    /\ state' = quorum_reached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

replicating_timeout_elapsed ==
    /\ state = replicating
    /\ state' = quorum_failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

quorum_pending_majority_acked ==
    /\ state = quorum_pending
    /\ state' = quorum_quorum_reached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

quorum_quorum_reached_replicas_failed ==
    /\ state = quorum_quorum_reached
    /\ state' = quorum_quorum_lost
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

quorum_quorum_lost_majority_restored ==
    /\ state = quorum_quorum_lost
    /\ state' = quorum_quorum_reached
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

quorum_quorum_lost_quorum_reset ==
    /\ state = quorum_quorum_lost
    /\ state' = quorum_pending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

lease_available_acquire ==
    /\ state = lease_available
    /\ state' = lease_held
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

lease_held_release ==
    /\ state = lease_held
    /\ state' = lease_available
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

lease_held_ttl_elapsed ==
    /\ state = lease_held
    /\ state' = lease_expired
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

lease_expired_cleanup ==
    /\ state = lease_expired
    /\ state' = lease_available
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ local_written_forward_to_replicas
    \/ replicating_majority_acked
    \/ replicating_timeout_elapsed
    \/ quorum_pending_majority_acked
    \/ quorum_quorum_reached_replicas_failed
    \/ quorum_quorum_lost_majority_restored
    \/ quorum_quorum_lost_quorum_reset
    \/ lease_available_acquire
    \/ lease_held_release
    \/ lease_held_ttl_elapsed
    \/ lease_expired_cleanup
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_replicating_to_quorum_reached_or_quorum_failed == SF_vars(replicating_majority_acked) \/ SF_vars(replicating_timeout_elapsed)
Fairness_quorum_pending_to_quorum_quorum_reached == SF_vars(quorum_pending_majority_acked)
Fairness_quorum_quorum_lost_to_quorum_quorum_reached_or_quorum_pending == WF_vars(quorum_quorum_lost_majority_restored) \/ WF_vars(quorum_quorum_lost_quorum_reset)
Fairness_lease_held_to_lease_available_or_lease_expired == WF_vars(lease_held_release) \/ WF_vars(lease_held_ttl_elapsed)
Fairness_lease_expired_to_lease_available == SF_vars(lease_expired_cleanup)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {quorum_reached, quorum_failed}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_bounded_replication == []((state = replicating) => (<>((state = quorum_reached) \/ (state = quorum_failed))))
Prop_Quorum_consistency_guarantee == []((state = quorum_quorum_reached) => (<>((state = quorum_quorum_reached) \/ (state = quorum_quorum_lost))))
Prop_Quorum_bounded_quorum_loss == []((state = quorum_quorum_lost) => (<>((state = quorum_quorum_reached) \/ (state = quorum_pending))))
Prop_Lease_exclusive_ownership == []((IF state = lease_held THEN 1 ELSE 0) <= (1))
Prop_Lease_bounded_lease == []((state = lease_held) => (<>((state = lease_available) \/ (state = lease_expired))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {quorum_reached, quorum_failed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_local_written == <>(state = local_written)
CanReach_replicating == <>(state = replicating)
CanReach_quorum_reached == <>(state = quorum_reached)
CanReach_quorum_failed == <>(state = quorum_failed)
CanReach_quorum_pending == <>(state = quorum_pending)
CanReach_quorum_quorum_reached == <>(state = quorum_quorum_reached)
CanReach_quorum_quorum_lost == <>(state = quorum_quorum_lost)
CanReach_lease_available == <>(state = lease_available)
CanReach_lease_held == <>(state = lease_held)
CanReach_lease_expired == <>(state = lease_expired)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     local_written = "local_written"
\*     replicating = "replicating"
\*     quorum_reached = "quorum_reached"
\*     quorum_failed = "quorum_failed"
\*     quorum_pending = "quorum_pending"
\*     quorum_quorum_reached = "quorum_quorum_reached"
\*     quorum_quorum_lost = "quorum_quorum_lost"
\*     lease_available = "lease_available"
\*     lease_held = "lease_held"
\*     lease_expired = "lease_expired"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=====================================================
