\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE DistributedCache_FailureDetection  -----------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { healthy, suspect, unhealthy, recovered, heartbeat_healthy, heartbeat_suspect, heartbeat_unhealthy }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
healthy == "healthy"
suspect == "suspect"
unhealthy == "unhealthy"
recovered == "recovered"
heartbeat_healthy == "heartbeat_healthy"
heartbeat_suspect == "heartbeat_suspect"
heartbeat_unhealthy == "heartbeat_unhealthy"

States == {
    healthy, suspect, unhealthy, recovered, heartbeat_healthy, heartbeat_suspect, heartbeat_unhealthy
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {healthy, heartbeat_healthy}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
healthy_heartbeat_received ==
    /\ state = healthy
    /\ state' = healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

healthy_heartbeat_missed ==
    /\ state = healthy
    /\ state' = suspect
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

suspect_heartbeat_received ==
    /\ state = suspect
    /\ state' = healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

suspect_timeout_elapsed ==
    /\ state = suspect
    /\ state' = unhealthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

unhealthy_recovery_detected ==
    /\ state = unhealthy
    /\ state' = recovered
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

recovered_reintegrated ==
    /\ state = recovered
    /\ state' = healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

heartbeat_healthy_heartbeat_received ==
    /\ state = heartbeat_healthy
    /\ state' = heartbeat_healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

heartbeat_healthy_heartbeat_missed ==
    /\ state = heartbeat_healthy
    /\ state' = heartbeat_suspect
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

heartbeat_suspect_heartbeat_received ==
    /\ state = heartbeat_suspect
    /\ state' = heartbeat_healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

heartbeat_suspect_timeout_elapsed ==
    /\ state = heartbeat_suspect
    /\ state' = heartbeat_unhealthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

heartbeat_unhealthy_recovery_detected ==
    /\ state = heartbeat_unhealthy
    /\ state' = heartbeat_healthy
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ healthy_heartbeat_received
    \/ healthy_heartbeat_missed
    \/ suspect_heartbeat_received
    \/ suspect_timeout_elapsed
    \/ unhealthy_recovery_detected
    \/ recovered_reintegrated
    \/ heartbeat_healthy_heartbeat_received
    \/ heartbeat_healthy_heartbeat_missed
    \/ heartbeat_suspect_heartbeat_received
    \/ heartbeat_suspect_timeout_elapsed
    \/ heartbeat_unhealthy_recovery_detected
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_suspect_to_healthy_or_unhealthy == SF_vars(suspect_heartbeat_received) \/ SF_vars(suspect_timeout_elapsed)
Fairness_unhealthy_to_recovered == WF_vars(unhealthy_recovery_detected)
Fairness_heartbeat_suspect_to_heartbeat_healthy_or_heartbeat_unhealthy == SF_vars(heartbeat_suspect_heartbeat_received) \/ SF_vars(heartbeat_suspect_timeout_elapsed)
Fairness_heartbeat_unhealthy_to_heartbeat_healthy == WF_vars(heartbeat_unhealthy_recovery_detected)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_bounded_detection == []((state = suspect) => (<>((state = healthy) \/ (state = unhealthy))))
Prop_eventual_recovery == []((state = unhealthy) => (<>((state = recovered) \/ (state = suspect))))
Prop_Heartbeat_bounded_detection == []((state = heartbeat_suspect) => (<>((state = heartbeat_healthy) \/ (state = heartbeat_unhealthy))))
Prop_Heartbeat_eventual_recovery == []((state = heartbeat_unhealthy) => (<>((state = heartbeat_healthy) \/ (state = heartbeat_suspect))))

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_healthy == <>(state = healthy)
CanReach_suspect == <>(state = suspect)
CanReach_unhealthy == <>(state = unhealthy)
CanReach_recovered == <>(state = recovered)
CanReach_heartbeat_healthy == <>(state = heartbeat_healthy)
CanReach_heartbeat_suspect == <>(state = heartbeat_suspect)
CanReach_heartbeat_unhealthy == <>(state = heartbeat_unhealthy)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     healthy = "healthy"
\*     suspect = "suspect"
\*     unhealthy = "unhealthy"
\*     recovered = "recovered"
\*     heartbeat_healthy = "heartbeat_healthy"
\*     heartbeat_suspect = "heartbeat_suspect"
\*     heartbeat_unhealthy = "heartbeat_unhealthy"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=====================================================
