\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------  MODULE ECommercePlatform_OrderSaga  -----------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { started, inventory_reserving, inventory_reserved, payment_processing, payment_completed, order_confirmed, compensating_inventory, order_cancelled, saga_pending, saga_completed, saga_failed, processmanager_idle, processmanager_running, processmanager_completed, processmanager_error, compensatingtransaction_idle, compensatingtransaction_executing, compensatingtransaction_completed, compensatingtransaction_compensating, compensatingtransaction_compensated, compensatingtransaction_compensation_failed }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
started == "started"
inventory_reserving == "inventory_reserving"
inventory_reserved == "inventory_reserved"
payment_processing == "payment_processing"
payment_completed == "payment_completed"
order_confirmed == "order_confirmed"
compensating_inventory == "compensating_inventory"
order_cancelled == "order_cancelled"
saga_pending == "saga_pending"
saga_completed == "saga_completed"
saga_failed == "saga_failed"
processmanager_idle == "processmanager_idle"
processmanager_running == "processmanager_running"
processmanager_completed == "processmanager_completed"
processmanager_error == "processmanager_error"
compensatingtransaction_idle == "compensatingtransaction_idle"
compensatingtransaction_executing == "compensatingtransaction_executing"
compensatingtransaction_completed == "compensatingtransaction_completed"
compensatingtransaction_compensating == "compensatingtransaction_compensating"
compensatingtransaction_compensated == "compensatingtransaction_compensated"
compensatingtransaction_compensation_failed == "compensatingtransaction_compensation_failed"

States == {
    started, inventory_reserving, inventory_reserved, payment_processing, payment_completed, order_confirmed, compensating_inventory, order_cancelled, saga_pending, saga_completed, saga_failed, processmanager_idle, processmanager_running, processmanager_completed, processmanager_error, compensatingtransaction_idle, compensatingtransaction_executing, compensatingtransaction_completed, compensatingtransaction_compensating, compensatingtransaction_compensated, compensatingtransaction_compensation_failed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {started, saga_pending, processmanager_idle, compensatingtransaction_idle}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
started_reserve_inventory ==
    /\ state = started
    /\ state' = inventory_reserving
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

inventory_reserving_reserve_success ==
    /\ state = inventory_reserving
    /\ state' = inventory_reserved
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

inventory_reserving_reserve_failed ==
    /\ state = inventory_reserving
    /\ state' = order_cancelled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

inventory_reserved_process_payment ==
    /\ state = inventory_reserved
    /\ state' = payment_processing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

payment_processing_payment_success ==
    /\ state = payment_processing
    /\ state' = payment_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

payment_processing_payment_failed ==
    /\ state = payment_processing
    /\ state' = compensating_inventory
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensating_inventory_compensation_done ==
    /\ state = compensating_inventory
    /\ state' = order_cancelled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

payment_completed_confirm_order ==
    /\ state = payment_completed
    /\ state' = order_confirmed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

saga_pending_success ==
    /\ state = saga_pending
    /\ state' = saga_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

saga_pending_failure ==
    /\ state = saga_pending
    /\ state' = saga_failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

processmanager_idle_start ==
    /\ state = processmanager_idle
    /\ state' = processmanager_running
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

processmanager_running_done ==
    /\ state = processmanager_running
    /\ state' = processmanager_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

processmanager_running_failure ==
    /\ state = processmanager_running
    /\ state' = processmanager_error
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensatingtransaction_idle_begin ==
    /\ state = compensatingtransaction_idle
    /\ state' = compensatingtransaction_executing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensatingtransaction_executing_success ==
    /\ state = compensatingtransaction_executing
    /\ state' = compensatingtransaction_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensatingtransaction_executing_failure ==
    /\ state = compensatingtransaction_executing
    /\ state' = compensatingtransaction_compensating
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensatingtransaction_compensating_compensation_success ==
    /\ state = compensatingtransaction_compensating
    /\ state' = compensatingtransaction_compensated
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

compensatingtransaction_compensating_compensation_failure ==
    /\ state = compensatingtransaction_compensating
    /\ state' = compensatingtransaction_compensation_failed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ started_reserve_inventory
    \/ inventory_reserving_reserve_success
    \/ inventory_reserving_reserve_failed
    \/ inventory_reserved_process_payment
    \/ payment_processing_payment_success
    \/ payment_processing_payment_failed
    \/ compensating_inventory_compensation_done
    \/ payment_completed_confirm_order
    \/ saga_pending_success
    \/ saga_pending_failure
    \/ processmanager_idle_start
    \/ processmanager_running_done
    \/ processmanager_running_failure
    \/ compensatingtransaction_idle_begin
    \/ compensatingtransaction_executing_success
    \/ compensatingtransaction_executing_failure
    \/ compensatingtransaction_compensating_compensation_success
    \/ compensatingtransaction_compensating_compensation_failure
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_inventory_reserving_to_inventory_reserved_or_order_cancelled == SF_vars(inventory_reserving_reserve_success) \/ SF_vars(inventory_reserving_reserve_failed)
Fairness_payment_processing_to_payment_completed_or_compensating_inventory == SF_vars(payment_processing_payment_success) \/ SF_vars(payment_processing_payment_failed)
Fairness_compensating_inventory_to_order_cancelled == SF_vars(compensating_inventory_compensation_done)
Fairness_saga_pending_to_saga_completed_or_saga_failed == SF_vars(saga_pending_success) \/ SF_vars(saga_pending_failure)
Fairness_processmanager_running_to_processmanager_completed_or_processmanager_error == WF_vars(processmanager_running_done) \/ WF_vars(processmanager_running_failure)
Fairness_compensatingtransaction_executing_to_compensatingtransaction_completed_or_compensatingtransaction_compensating == SF_vars(compensatingtransaction_executing_success) \/ SF_vars(compensatingtransaction_executing_failure)
Fairness_compensatingtransaction_compensating_to_compensatingtransaction_compensated_or_compensatingtransaction_compensation_failed == SF_vars(compensatingtransaction_compensating_compensation_success) \/ SF_vars(compensatingtransaction_compensating_compensation_failure)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {order_confirmed, order_cancelled, saga_completed, saga_failed, processmanager_completed, processmanager_error, compensatingtransaction_completed, compensatingtransaction_compensated, compensatingtransaction_compensation_failed}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_completion == []((state = started) => (<>((state = order_confirmed) \/ (state = order_cancelled))))
Prop_consistency == []((state = compensating_inventory) => (<>(state = order_cancelled)))
Prop_Saga_eventual_completion == []((state = saga_pending) => (<>((state = saga_completed) \/ (state = saga_failed))))
Prop_CompensatingTransaction_ReserveInventory_eventual_completion == []((state = compensatingtransaction_executing) => (<>((state = compensatingtransaction_completed) \/ (state = compensatingtransaction_compensating))))
Prop_CompensatingTransaction_ReserveInventory_bounded_compensation == []((state = compensatingtransaction_compensating) => (<>((state = compensatingtransaction_compensated) \/ (state = compensatingtransaction_compensation_failed))))
Prop_CompensatingTransaction_ReserveInventory_consistency_restored == []((state = compensatingtransaction_compensated) => (TRUE))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {order_confirmed, order_cancelled, saga_completed, saga_failed, processmanager_completed, processmanager_error, compensatingtransaction_completed, compensatingtransaction_compensated, compensatingtransaction_compensation_failed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_started == <>(state = started)
CanReach_inventory_reserving == <>(state = inventory_reserving)
CanReach_inventory_reserved == <>(state = inventory_reserved)
CanReach_payment_processing == <>(state = payment_processing)
CanReach_payment_completed == <>(state = payment_completed)
CanReach_order_confirmed == <>(state = order_confirmed)
CanReach_compensating_inventory == <>(state = compensating_inventory)
CanReach_order_cancelled == <>(state = order_cancelled)
CanReach_saga_pending == <>(state = saga_pending)
CanReach_saga_completed == <>(state = saga_completed)
CanReach_saga_failed == <>(state = saga_failed)
CanReach_processmanager_idle == <>(state = processmanager_idle)
CanReach_processmanager_running == <>(state = processmanager_running)
CanReach_processmanager_completed == <>(state = processmanager_completed)
CanReach_processmanager_error == <>(state = processmanager_error)
CanReach_compensatingtransaction_idle == <>(state = compensatingtransaction_idle)
CanReach_compensatingtransaction_executing == <>(state = compensatingtransaction_executing)
CanReach_compensatingtransaction_completed == <>(state = compensatingtransaction_completed)
CanReach_compensatingtransaction_compensating == <>(state = compensatingtransaction_compensating)
CanReach_compensatingtransaction_compensated == <>(state = compensatingtransaction_compensated)
CanReach_compensatingtransaction_compensation_failed == <>(state = compensatingtransaction_compensation_failed)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     started = "started"
\*     inventory_reserving = "inventory_reserving"
\*     inventory_reserved = "inventory_reserved"
\*     payment_processing = "payment_processing"
\*     payment_completed = "payment_completed"
\*     order_confirmed = "order_confirmed"
\*     compensating_inventory = "compensating_inventory"
\*     order_cancelled = "order_cancelled"
\*     saga_pending = "saga_pending"
\*     saga_completed = "saga_completed"
\*     saga_failed = "saga_failed"
\*     processmanager_idle = "processmanager_idle"
\*     processmanager_running = "processmanager_running"
\*     processmanager_completed = "processmanager_completed"
\*     processmanager_error = "processmanager_error"
\*     compensatingtransaction_idle = "compensatingtransaction_idle"
\*     compensatingtransaction_executing = "compensatingtransaction_executing"
\*     compensatingtransaction_completed = "compensatingtransaction_completed"
\*     compensatingtransaction_compensating = "compensatingtransaction_compensating"
\*     compensatingtransaction_compensated = "compensatingtransaction_compensated"
\*     compensatingtransaction_compensation_failed = "compensatingtransaction_compensation_failed"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

===============================================
