\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------------  MODULE ECommercePlatform_EventSourcing  ---------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, appending, persisted, eventsourced_active, eventsourced_inactive }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
appending == "appending"
persisted == "persisted"
eventsourced_active == "eventsourced_active"
eventsourced_inactive == "eventsourced_inactive"

States == {
    idle, appending, persisted, eventsourced_active, eventsourced_inactive
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
idle_append_event ==
    /\ state = idle
    /\ state' = appending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

appending_write_success ==
    /\ state = appending
    /\ state' = persisted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ idle_append_event
    \/ appending_write_success
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_appending_to_persisted == SF_vars(appending_write_success)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {persisted}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_durability == []((state = appending) => (<>(state = persisted)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {persisted})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_appending == <>(state = appending)
CanReach_persisted == <>(state = persisted)
CanReach_eventsourced_active == <>(state = eventsourced_active)
CanReach_eventsourced_inactive == <>(state = eventsourced_inactive)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     appending = "appending"
\*     persisted = "persisted"
\*     eventsourced_active = "eventsourced_active"
\*     eventsourced_inactive = "eventsourced_inactive"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

===================================================
