\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------------------  MODULE ECommercePlatform_CriticalOrderCommit  ---------------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, preparing, prepared, committing, committed, aborting, aborted, twophasecommit_idle, twophasecommit_preparing, twophasecommit_prepared, twophasecommit_committing, twophasecommit_committed, twophasecommit_aborting, twophasecommit_aborted }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
preparing == "preparing"
prepared == "prepared"
committing == "committing"
committed == "committed"
aborting == "aborting"
aborted == "aborted"
twophasecommit_idle == "twophasecommit_idle"
twophasecommit_preparing == "twophasecommit_preparing"
twophasecommit_prepared == "twophasecommit_prepared"
twophasecommit_committing == "twophasecommit_committing"
twophasecommit_committed == "twophasecommit_committed"
twophasecommit_aborting == "twophasecommit_aborting"
twophasecommit_aborted == "twophasecommit_aborted"

States == {
    idle, preparing, prepared, committing, committed, aborting, aborted, twophasecommit_idle, twophasecommit_preparing, twophasecommit_prepared, twophasecommit_committing, twophasecommit_committed, twophasecommit_aborting, twophasecommit_aborted
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {idle, twophasecommit_idle}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
idle_begin ==
    /\ state = idle
    /\ state' = preparing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

preparing_all_voted_yes ==
    /\ state = preparing
    /\ state' = prepared
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

preparing_any_voted_no ==
    /\ state = preparing
    /\ state' = aborting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

preparing_timeout_elapsed ==
    /\ state = preparing
    /\ state' = aborting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

prepared_commit_command ==
    /\ state = prepared
    /\ state' = committing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

committing_all_acked ==
    /\ state = committing
    /\ state' = committed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

aborting_all_acked ==
    /\ state = aborting
    /\ state' = aborted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_idle_begin ==
    /\ state = twophasecommit_idle
    /\ state' = twophasecommit_preparing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_preparing_all_voted_yes ==
    /\ state = twophasecommit_preparing
    /\ state' = twophasecommit_prepared
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_preparing_any_voted_no ==
    /\ state = twophasecommit_preparing
    /\ state' = twophasecommit_aborting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_preparing_timeout_elapsed ==
    /\ state = twophasecommit_preparing
    /\ state' = twophasecommit_aborting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_prepared_commit_command ==
    /\ state = twophasecommit_prepared
    /\ state' = twophasecommit_committing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_committing_all_acked ==
    /\ state = twophasecommit_committing
    /\ state' = twophasecommit_committed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

twophasecommit_aborting_all_acked ==
    /\ state = twophasecommit_aborting
    /\ state' = twophasecommit_aborted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ idle_begin
    \/ preparing_all_voted_yes
    \/ preparing_any_voted_no
    \/ preparing_timeout_elapsed
    \/ prepared_commit_command
    \/ committing_all_acked
    \/ aborting_all_acked
    \/ twophasecommit_idle_begin
    \/ twophasecommit_preparing_all_voted_yes
    \/ twophasecommit_preparing_any_voted_no
    \/ twophasecommit_preparing_timeout_elapsed
    \/ twophasecommit_prepared_commit_command
    \/ twophasecommit_committing_all_acked
    \/ twophasecommit_aborting_all_acked
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_preparing_to_prepared_or_aborting == SF_vars(preparing_all_voted_yes) \/ SF_vars(preparing_any_voted_no) \/ SF_vars(preparing_timeout_elapsed)
Fairness_committing_to_committed == SF_vars(committing_all_acked)
Fairness_aborting_to_aborted == SF_vars(aborting_all_acked)
Fairness_twophasecommit_preparing_to_twophasecommit_prepared_or_twophasecommit_aborting == SF_vars(twophasecommit_preparing_all_voted_yes) \/ SF_vars(twophasecommit_preparing_any_voted_no) \/ SF_vars(twophasecommit_preparing_timeout_elapsed)
Fairness_twophasecommit_committing_to_twophasecommit_committed == SF_vars(twophasecommit_committing_all_acked)
Fairness_twophasecommit_aborting_to_twophasecommit_aborted == SF_vars(twophasecommit_aborting_all_acked)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {committed, aborted, twophasecommit_committed, twophasecommit_aborted}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_atomic_outcome == [](<>((state = committed) \/ (state = aborted)))
Prop_TwoPhaseCommit_atomic_outcome == [](<>((state = twophasecommit_committed) \/ (state = twophasecommit_aborted)))
Prop_TwoPhaseCommit_uniform_decision == []((state = twophasecommit_committed) => (TRUE))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {committed, aborted, twophasecommit_committed, twophasecommit_aborted})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_preparing == <>(state = preparing)
CanReach_prepared == <>(state = prepared)
CanReach_committing == <>(state = committing)
CanReach_committed == <>(state = committed)
CanReach_aborting == <>(state = aborting)
CanReach_aborted == <>(state = aborted)
CanReach_twophasecommit_idle == <>(state = twophasecommit_idle)
CanReach_twophasecommit_preparing == <>(state = twophasecommit_preparing)
CanReach_twophasecommit_prepared == <>(state = twophasecommit_prepared)
CanReach_twophasecommit_committing == <>(state = twophasecommit_committing)
CanReach_twophasecommit_committed == <>(state = twophasecommit_committed)
CanReach_twophasecommit_aborting == <>(state = twophasecommit_aborting)
CanReach_twophasecommit_aborted == <>(state = twophasecommit_aborted)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     preparing = "preparing"
\*     prepared = "prepared"
\*     committing = "committing"
\*     committed = "committed"
\*     aborting = "aborting"
\*     aborted = "aborted"
\*     twophasecommit_idle = "twophasecommit_idle"
\*     twophasecommit_preparing = "twophasecommit_preparing"
\*     twophasecommit_prepared = "twophasecommit_prepared"
\*     twophasecommit_committing = "twophasecommit_committing"
\*     twophasecommit_committed = "twophasecommit_committed"
\*     twophasecommit_aborting = "twophasecommit_aborting"
\*     twophasecommit_aborted = "twophasecommit_aborted"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=========================================================
