\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------  MODULE ECommercePlatform_NotificationDelivery  ----------------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { pending, sending, delivered, retrying, dead, deadletterqueue_empty, deadletterqueue_has_messages, deadletterqueue_processing_retry, deadletterqueue_discarded }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
pending == "pending"
sending == "sending"
delivered == "delivered"
retrying == "retrying"
dead == "dead"
deadletterqueue_empty == "deadletterqueue_empty"
deadletterqueue_has_messages == "deadletterqueue_has_messages"
deadletterqueue_processing_retry == "deadletterqueue_processing_retry"
deadletterqueue_discarded == "deadletterqueue_discarded"

States == {
    pending, sending, delivered, retrying, dead, deadletterqueue_empty, deadletterqueue_has_messages, deadletterqueue_processing_retry, deadletterqueue_discarded
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Int;
    attempts,    \* Data variable (extracted)
    \* @type: Int;
    max_retries     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Int, Int>>;
vars == <<state, pc, history, event_queue, attempts, max_retries>>

Init ==
    /\ state \in {pending, deadletterqueue_empty}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ attempts = 0
    /\ max_retries = 0

\* Transition actions
pending_send_request ==
    /\ state = pending
    /\ state' = sending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

sending_send_success ==
    /\ state = sending
    /\ state' = delivered
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

sending_send_failure_retrying ==
    /\ state = sending
    /\ (attempts < max_retries)
    /\ state' = retrying
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

sending_send_failure_dead ==
    /\ state = sending
    /\ (attempts >= max_retries)
    /\ state' = dead
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

retrying_retry ==
    /\ state = retrying
    /\ state' = sending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

retrying_max_retries_exceeded ==
    /\ state = retrying
    /\ state' = dead
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_empty_message_failed ==
    /\ state = deadletterqueue_empty
    /\ state' = deadletterqueue_has_messages
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_has_messages_retry_requested ==
    /\ state = deadletterqueue_has_messages
    /\ state' = deadletterqueue_processing_retry
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_processing_retry_retry_succeeded ==
    /\ state = deadletterqueue_processing_retry
    /\ state' = deadletterqueue_empty
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_processing_retry_retry_failed ==
    /\ state = deadletterqueue_processing_retry
    /\ state' = deadletterqueue_has_messages
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_processing_retry_max_retries_exceeded ==
    /\ state = deadletterqueue_processing_retry
    /\ state' = deadletterqueue_discarded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

deadletterqueue_has_messages_retention_expired ==
    /\ state = deadletterqueue_has_messages
    /\ state' = deadletterqueue_discarded
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<attempts, max_retries>>

Next ==
    \/ pending_send_request
    \/ sending_send_success
    \/ sending_send_failure_retrying
    \/ sending_send_failure_dead
    \/ retrying_retry
    \/ retrying_max_retries_exceeded
    \/ deadletterqueue_empty_message_failed
    \/ deadletterqueue_has_messages_retry_requested
    \/ deadletterqueue_processing_retry_retry_succeeded
    \/ deadletterqueue_processing_retry_retry_failed
    \/ deadletterqueue_processing_retry_max_retries_exceeded
    \/ deadletterqueue_has_messages_retention_expired
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_pending_to_sending == SF_vars(pending_send_request)
Fairness_retrying_to_sending_or_dead == SF_vars(retrying_retry) \/ SF_vars(retrying_max_retries_exceeded)
Fairness_deadletterqueue_has_messages_to_deadletterqueue_processing_retry_or_deadletterqueue_discarded == SF_vars(deadletterqueue_has_messages_retry_requested) \/ SF_vars(deadletterqueue_has_messages_retention_expired)
Fairness_deadletterqueue_processing_retry_to_deadletterqueue_empty_or_deadletterqueue_has_messages_or_deadletterqueue_discarded == WF_vars(deadletterqueue_processing_retry_retry_succeeded) \/ WF_vars(deadletterqueue_processing_retry_retry_failed) \/ WF_vars(deadletterqueue_processing_retry_max_retries_exceeded)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {delivered, dead, deadletterqueue_discarded}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_delivery == []((state = pending) => (<>((state = delivered) \/ (state = dead))))
Prop_bounded_retries == []((state = retrying) => (<>((state = sending) \/ (state = dead))))
Prop_DeadLetterQueue_bounded_retention == []((state = deadletterqueue_has_messages) => (<>((state = deadletterqueue_empty) \/ (state = deadletterqueue_discarded))))
Prop_DeadLetterQueue_eventual_retry == []((state = deadletterqueue_has_messages) => (<>((state = deadletterqueue_processing_retry) \/ (state = deadletterqueue_discarded))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {delivered, dead, deadletterqueue_discarded})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_pending == <>(state = pending)
CanReach_sending == <>(state = sending)
CanReach_delivered == <>(state = delivered)
CanReach_retrying == <>(state = retrying)
CanReach_dead == <>(state = dead)
CanReach_deadletterqueue_empty == <>(state = deadletterqueue_empty)
CanReach_deadletterqueue_has_messages == <>(state = deadletterqueue_has_messages)
CanReach_deadletterqueue_processing_retry == <>(state = deadletterqueue_processing_retry)
CanReach_deadletterqueue_discarded == <>(state = deadletterqueue_discarded)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     pending = "pending"
\*     sending = "sending"
\*     delivered = "delivered"
\*     retrying = "retrying"
\*     dead = "dead"
\*     deadletterqueue_empty = "deadletterqueue_empty"
\*     deadletterqueue_has_messages = "deadletterqueue_has_messages"
\*     deadletterqueue_processing_retry = "deadletterqueue_processing_retry"
\*     deadletterqueue_discarded = "deadletterqueue_discarded"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==========================================================
