\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------------  MODULE ECommercePlatform_OrderProjection  -----------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { write_ready, write_pending, read_stale, read_synced, cqrs_write_ready, cqrs_write_pending, cqrs_read_stale, cqrs_read_synced }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
write_ready == "write_ready"
write_pending == "write_pending"
read_stale == "read_stale"
read_synced == "read_synced"
cqrs_write_ready == "cqrs_write_ready"
cqrs_write_pending == "cqrs_write_pending"
cqrs_read_stale == "cqrs_read_stale"
cqrs_read_synced == "cqrs_read_synced"

States == {
    write_ready, write_pending, read_stale, read_synced, cqrs_write_ready, cqrs_write_pending, cqrs_read_stale, cqrs_read_synced
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state \in {write_ready, cqrs_write_ready}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
write_ready_order_event ==
    /\ state = write_ready
    /\ state' = write_pending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

write_pending_event_applied ==
    /\ state = write_pending
    /\ state' = write_ready
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

write_pending_projection_lag ==
    /\ state = write_pending
    /\ state' = read_stale
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

read_stale_projection_sync ==
    /\ state = read_stale
    /\ state' = read_synced
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

cqrs_write_ready_command ==
    /\ state = cqrs_write_ready
    /\ state' = cqrs_write_pending
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

cqrs_write_pending_command_applied ==
    /\ state = cqrs_write_pending
    /\ state' = cqrs_write_ready
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

cqrs_write_pending_projection_lag ==
    /\ state = cqrs_write_pending
    /\ state' = cqrs_read_stale
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

cqrs_read_stale_projection_caught_up ==
    /\ state = cqrs_read_stale
    /\ state' = cqrs_read_synced
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

cqrs_read_synced_command ==
    /\ state = cqrs_read_synced
    /\ state' = cqrs_read_stale
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ write_ready_order_event
    \/ write_pending_event_applied
    \/ write_pending_projection_lag
    \/ read_stale_projection_sync
    \/ cqrs_write_ready_command
    \/ cqrs_write_pending_command_applied
    \/ cqrs_write_pending_projection_lag
    \/ cqrs_read_stale_projection_caught_up
    \/ cqrs_read_synced_command
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_write_pending_to_write_ready == SF_vars(write_pending_event_applied)
Fairness_read_stale_to_read_synced == SF_vars(read_stale_projection_sync)
Fairness_cqrs_write_pending_to_cqrs_write_ready == SF_vars(cqrs_write_pending_command_applied)
Fairness_cqrs_read_stale_to_cqrs_read_synced == SF_vars(cqrs_read_stale_projection_caught_up)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_consistency == []((state = read_stale) => (<>(state = read_synced)))
Prop_CQRS_eventual_consistency == []((state = cqrs_read_stale) => (<>(state = cqrs_read_synced)))
Prop_CQRS_write_availability == []((state = cqrs_write_pending) => (<>(state = cqrs_write_ready)))

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](ENABLED(Next))

\* Reachability helpers for model checking
CanReach_write_ready == <>(state = write_ready)
CanReach_write_pending == <>(state = write_pending)
CanReach_read_stale == <>(state = read_stale)
CanReach_read_synced == <>(state = read_synced)
CanReach_cqrs_write_ready == <>(state = cqrs_write_ready)
CanReach_cqrs_write_pending == <>(state = cqrs_write_pending)
CanReach_cqrs_read_stale == <>(state = cqrs_read_stale)
CanReach_cqrs_read_synced == <>(state = cqrs_read_synced)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     write_ready = "write_ready"
\*     write_pending = "write_pending"
\*     read_stale = "read_stale"
\*     read_synced = "read_synced"
\*     cqrs_write_ready = "cqrs_write_ready"
\*     cqrs_write_pending = "cqrs_write_pending"
\*     cqrs_read_stale = "cqrs_read_stale"
\*     cqrs_read_synced = "cqrs_read_synced"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=====================================================
