\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
----------------------------------------------  MODULE ECommercePlatform_InventoryReservation  ----------------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { available, reserving, reserved, conflict, optimisticlocking_unlocked, optimisticlocking_reading, optimisticlocking_writing, optimisticlocking_conflict, optimisticlocking_committed, timeout_pending, timeout_completed, timeout_timed_out }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
available == "available"
reserving == "reserving"
reserved == "reserved"
conflict == "conflict"
optimisticlocking_unlocked == "optimisticlocking_unlocked"
optimisticlocking_reading == "optimisticlocking_reading"
optimisticlocking_writing == "optimisticlocking_writing"
optimisticlocking_conflict == "optimisticlocking_conflict"
optimisticlocking_committed == "optimisticlocking_committed"
timeout_pending == "timeout_pending"
timeout_completed == "timeout_completed"
timeout_timed_out == "timeout_timed_out"

States == {
    available, reserving, reserved, conflict, optimisticlocking_unlocked, optimisticlocking_reading, optimisticlocking_writing, optimisticlocking_conflict, optimisticlocking_committed, timeout_pending, timeout_completed, timeout_timed_out
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Int;
    quantity     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Int>>;
vars == <<state, pc, history, event_queue, quantity>>

Init ==
    /\ state \in {available, optimisticlocking_unlocked, timeout_pending}
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ quantity = 0

\* Transition actions
available_reserve_request ==
    /\ state = available
    /\ state' = reserving
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

reserving_version_match ==
    /\ state = reserving
    /\ (quantity > 0)
    /\ state' = reserved
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

reserving_version_mismatch ==
    /\ state = reserving
    /\ state' = conflict
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_unlocked_read_begin ==
    /\ state = optimisticlocking_unlocked
    /\ state' = optimisticlocking_reading
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_reading_write_prepare ==
    /\ state = optimisticlocking_reading
    /\ state' = optimisticlocking_writing
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_writing_version_match ==
    /\ state = optimisticlocking_writing
    /\ state' = optimisticlocking_committed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_writing_version_mismatch ==
    /\ state = optimisticlocking_writing
    /\ state' = optimisticlocking_conflict
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_reading_read_abort ==
    /\ state = optimisticlocking_reading
    /\ state' = optimisticlocking_unlocked
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

optimisticlocking_writing_write_abort ==
    /\ state = optimisticlocking_writing
    /\ state' = optimisticlocking_unlocked
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

timeout_pending_success ==
    /\ state = timeout_pending
    /\ state' = timeout_completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

timeout_pending_timeout ==
    /\ state = timeout_pending
    /\ state' = timeout_timed_out
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<quantity>>

Next ==
    \/ available_reserve_request
    \/ reserving_version_match
    \/ reserving_version_mismatch
    \/ optimisticlocking_unlocked_read_begin
    \/ optimisticlocking_reading_write_prepare
    \/ optimisticlocking_writing_version_match
    \/ optimisticlocking_writing_version_mismatch
    \/ optimisticlocking_reading_read_abort
    \/ optimisticlocking_writing_write_abort
    \/ timeout_pending_success
    \/ timeout_pending_timeout
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_reserving_to_reserved_or_conflict == SF_vars(reserving_version_match) \/ SF_vars(reserving_version_mismatch)
Fairness_optimisticlocking_writing_to_optimisticlocking_committed_or_optimisticlocking_conflict_or_optimisticlocking_unlocked == SF_vars(optimisticlocking_writing_version_match) \/ SF_vars(optimisticlocking_writing_version_mismatch) \/ SF_vars(optimisticlocking_writing_write_abort)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {reserved, conflict, optimisticlocking_conflict, optimisticlocking_committed, timeout_completed, timeout_timed_out}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_no_oversell == []((state = reserving) => (<>((state = reserved) \/ (state = conflict))))
Prop_OptimisticLocking_no_lost_updates == []((state = optimisticlocking_writing) => (<>((state = optimisticlocking_committed) \/ (state = optimisticlocking_conflict))))
Prop_OptimisticLocking_conflict_detection == []((state = optimisticlocking_conflict) => (TRUE))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {reserved, conflict, optimisticlocking_conflict, optimisticlocking_committed, timeout_completed, timeout_timed_out})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_available == <>(state = available)
CanReach_reserving == <>(state = reserving)
CanReach_reserved == <>(state = reserved)
CanReach_conflict == <>(state = conflict)
CanReach_optimisticlocking_unlocked == <>(state = optimisticlocking_unlocked)
CanReach_optimisticlocking_reading == <>(state = optimisticlocking_reading)
CanReach_optimisticlocking_writing == <>(state = optimisticlocking_writing)
CanReach_optimisticlocking_conflict == <>(state = optimisticlocking_conflict)
CanReach_optimisticlocking_committed == <>(state = optimisticlocking_committed)
CanReach_timeout_pending == <>(state = timeout_pending)
CanReach_timeout_completed == <>(state = timeout_completed)
CanReach_timeout_timed_out == <>(state = timeout_timed_out)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     available = "available"
\*     reserving = "reserving"
\*     reserved = "reserved"
\*     conflict = "conflict"
\*     optimisticlocking_unlocked = "optimisticlocking_unlocked"
\*     optimisticlocking_reading = "optimisticlocking_reading"
\*     optimisticlocking_writing = "optimisticlocking_writing"
\*     optimisticlocking_conflict = "optimisticlocking_conflict"
\*     optimisticlocking_committed = "optimisticlocking_committed"
\*     timeout_pending = "timeout_pending"
\*     timeout_completed = "timeout_completed"
\*     timeout_timed_out = "timeout_timed_out"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==========================================================
