\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------  MODULE BoundedExample_CounterBehavior  --------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle, counting, finished }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"
counting == "counting"
finished == "finished"

States == {
    idle, counting, finished
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Int;
    counter,    \* Data variable (extracted)
    \* @type: Int;
    level,    \* Data variable (extracted)
    \* @type: Str;
    status     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Int, Int, Str>>;
vars == <<state, pc, history, event_queue, counter, level, status>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ counter = 0
    /\ level = 1
    /\ status = "pending"

\* Transition actions
idle_start ==
    /\ state = idle
    /\ state' = counting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<counter, level, status>>

counting_increment ==
    /\ state = counting
    /\ state' = counting
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ counter' = (counter + 1)
    /\ UNCHANGED <<level, status>>

counting_finish ==
    /\ state = counting
    /\ (counter >= 10)
    /\ state' = finished
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<counter, level, status>>

Next ==
    \/ idle_start
    \/ counting_increment
    \/ counting_finish
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)
    /\ counter >= 0
    /\ counter <= 100
    /\ level >= 1
    /\ level <= 10
    /\ status \in {"pending", "active", "done"}

\* Terminal states
TerminalStates == {finished}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_completion == []((state = counting) => (<>(state = finished)))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {finished})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)
CanReach_counting == <>(state = counting)
CanReach_finished == <>(state = finished)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*     counting = "counting"
\*     finished = "finished"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

==================================================
