\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------  MODULE Minimal3_Test  ---------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { idle }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
idle == "idle"

States == {
    idle
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Str;
    status     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Str>>;
vars == <<state, pc, history, event_queue, status>>

Init ==
    /\ state = idle
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ status = "pending"

\* Transition actions
Next ==
    UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)
    /\ status \in {"pending", "active"}

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Reachability helpers for model checking
CanReach_idle == <>(state = idle)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     idle = "idle"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

=================================
