\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
--------------------------------------------  MODULE TLAPrimitivesDemo_QuantifierExamples  --------------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { validating, validated }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
validating == "validating"
validated == "validated"

States == {
    validating, validated
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = validating
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
validating_validate ==
    /\ state = validating
    /\ state' = validated
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ validating_validate
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {validated}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* User-defined invariants
Inv_all_orders_valid ==
    \A amount \in {1, 5, 10, 50, 100} : (amount > 0)

Inv_exists_high_priority ==
    \E priority \in {1, 3, 5, 7, 10} : (priority >= 5)

Inv_nested_quantifier ==
    \A c \in {1, 2, 3} : \E o \in {1, 2, 3, 4, 5} : (o >= c)

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {validated})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_validating == <>(state = validating)
CanReach_validated == <>(state = validated)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     validating = "validating"
\*     validated = "validated"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

========================================================
