\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
------------------------------------  MODULE TaskManager_UserRegistration  ------------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { anonymous, pending_verification, active, suspended, deleted }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
anonymous == "anonymous"
pending_verification == "pending_verification"
active == "active"
suspended == "suspended"
deleted == "deleted"

States == {
    anonymous, pending_verification, active, suspended, deleted
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue     \* Pending events/messages queue

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str })>>;
vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = anonymous
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
anonymous_register ==
    /\ state = anonymous
    /\ state' = pending_verification
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

pending_verification_verify ==
    /\ state = pending_verification
    /\ state' = active
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

pending_verification_expire ==
    /\ state = pending_verification
    /\ state' = anonymous
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

active_suspend ==
    /\ state = active
    /\ state' = suspended
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

suspended_reinstate ==
    /\ state = suspended
    /\ state' = active
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

active_delete ==
    /\ state = active
    /\ state' = deleted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

suspended_delete ==
    /\ state = suspended
    /\ state' = deleted
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ anonymous_register
    \/ pending_verification_verify
    \/ pending_verification_expire
    \/ active_suspend
    \/ suspended_reinstate
    \/ active_delete
    \/ suspended_delete
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_pending_verification_to_active_or_anonymous == SF_vars(pending_verification_verify) \/ SF_vars(pending_verification_expire)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ SF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {deleted}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {deleted})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_anonymous == <>(state = anonymous)
CanReach_pending_verification == <>(state = pending_verification)
CanReach_active == <>(state = active)
CanReach_suspended == <>(state = suspended)
CanReach_deleted == <>(state = deleted)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     anonymous = "anonymous"
\*     pending_verification = "pending_verification"
\*     active = "active"
\*     suspended = "suspended"
\*     deleted = "deleted"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

================================================
