\* AUTO-GENERATED by Intent compiler — do not edit by hand.
\* Re-generate with: intent compile <source>.intent
---------------------------------  MODULE TaskManager_TaskLifecycle  ---------------------------------
EXTENDS Naturals, Sequences, TLC

\* State values (defined as strings for Apalache)
created == "created"
assigned == "assigned"
in_progress == "in_progress"
completed == "completed"
cancelled == "cancelled"

States == {
    created, assigned, in_progress, completed, cancelled
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq(Str);
    event_queue     \* Pending events/messages queue

vars == <<state, pc, history, event_queue>>

Init ==
    /\ state = created
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>

\* Transition actions
created_assign ==
    /\ state = created
    /\ state' = assigned
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

created_cancel ==
    /\ state = created
    /\ state' = cancelled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

assigned_start ==
    /\ state = assigned
    /\ state' = in_progress
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

assigned_cancel ==
    /\ state = assigned
    /\ state' = cancelled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

in_progress_finish ==
    /\ state = in_progress
    /\ state' = completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

in_progress_cancel ==
    /\ state = in_progress
    /\ state' = cancelled
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue

Next ==
    \/ created_assign
    \/ created_cancel
    \/ assigned_start
    \/ assigned_cancel
    \/ in_progress_finish
    \/ in_progress_cancel
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

\* Fairness conditions
Fairness_created_to_assigned == WF_vars(created_assign)
Fairness_assigned_to_in_progress == WF_vars(assigned_start)
Fairness_in_progress_to_completed == WF_vars(in_progress_finish)

Spec ==
    /\ Init
    /\ [][Next]_vars
    /\ WF_vars(Next)
    /\ WF_vars(Next)
    /\ WF_vars(Next)

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {completed, cancelled}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Temporal properties (LTL)
Prop_eventual_completion == []((state = created) => (<>((state = completed) \/ (state = cancelled))))

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {completed, cancelled})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_created == <>(state = created)
CanReach_assigned == <>(state = assigned)
CanReach_in_progress == <>(state = in_progress)
CanReach_completed == <>(state = completed)
CanReach_cancelled == <>(state = cancelled)

=============================================
