\* AUTO-GENERATED by Intent compiler – do not edit by hand.
\* Re-generate with: intent compile <source>.intent
-----------------------------------  MODULE MessageTest_OrderProcessing  -----------------------------------
EXTENDS Naturals, Sequences, Apalache, Variants

\* ═══════════════════════════════════════════════════════════════════════════
\* APALACHE TYPE ANNOTATIONS
\* ═══════════════════════════════════════════════════════════════════════════

\* @typeAlias: STATE = Str;
\* @typeAlias: STATES = Set(STATE);  \* { pending, payment_requested, completed }

\* @typeAlias: EVENT = { type: Str };
\* @typeAlias: EVENT_QUEUE = Seq(EVENT);

\* @typeAlias: HISTORY = Seq(STATE);

\* State values (defined as strings for Apalache)
pending == "pending"
payment_requested == "payment_requested"
completed == "completed"

States == {
    pending, payment_requested, completed
}

VARIABLES
    \* @type: Str;
    state,      \* Current state
    \* @type: Int;
    pc,         \* Program counter for step tracking
    \* @type: Seq(Str);
    history,    \* Sequence of visited states (for trace analysis)
    \* @type: Seq({ type: Str });
    event_queue,    \* Pending events/messages queue
    \* @type: Seq({ type: Str, arg0: Str, arg1: Int });
    PaymentService_queue,    \* Message queue for PaymentService
    \* @type: Str;
    orderID     \* Data variable (extracted)

\* @type: <<Str, Int, Seq(Str), Seq({ type: Str }), Seq({ type: Str, arg0: Str, arg1: Int }), Str>>;
vars == <<state, pc, history, event_queue, PaymentService_queue, orderID>>

Init ==
    /\ state = pending
    /\ pc = 0
    /\ history = <<>>
    /\ event_queue = <<>>
    /\ PaymentService_queue = <<>>
    /\ orderID = ""

\* Transition actions
pending_create ==
    /\ state = pending
    /\ state' = payment_requested
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ PaymentService_queue' = PaymentService_queue \o <<[type |-> "PaymentRequested", arg0 |-> orderID, arg1 |-> 100]>>
    /\ orderID' = "123"

payment_requested_payment_done ==
    /\ state = payment_requested
    /\ state' = completed
    /\ pc' = pc + 1
    /\ history' = Append(history, state)
    /\ event_queue' = event_queue
    /\ UNCHANGED <<PaymentService_queue, orderID>>

Next ==
    \/ pending_create
    \/ payment_requested_payment_done
    \/ UNCHANGED vars

\* Stuttering step (system does nothing)
Stutter ==
    UNCHANGED vars

Spec ==
    /\ Init
    /\ [][Next]_vars

\* Type invariant
TypeOK ==
    /\ state \in States
    /\ pc \in Nat
    \* history: checked via HistoryConsistent (Seq(States) unsupported by Apalache)

\* Terminal states
TerminalStates == {completed}

\* Once in terminal state, cannot leave
TerminalStable ==
    (state \in TerminalStates) => (state' \in TerminalStates)

\* History length matches step count
HistoryConsistent ==
    Len(history) = pc

\* Liveness: Eventually reaches a terminal state
Liveness ==
    <>(state \in {completed})

\* Deadlock freedom: From every non-terminal state, some action is enabled
DeadlockFree ==
    [](state \notin TerminalStates => ENABLED(Next))

\* Reachability helpers for model checking
CanReach_pending == <>(state = pending)
CanReach_payment_requested == <>(state = payment_requested)
CanReach_completed == <>(state = completed)

\* Model checking configuration
\* Use with TLC or Apalache:
\*   CONSTANTS
\*     pending = "pending"
\*     payment_requested = "payment_requested"
\*     completed = "completed"
\*   SPECIFICATION Spec
\*   INVARIANTS TypeOK, HistoryConsistent
\*   PROPERTIES Liveness, TerminalStable

===============================================
